// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminSearchMemoriesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminSearchMemoriesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .memory.v1.AdminMemoryItem items = 1;</code>
   */
  java.util.List<io.github.chirino.memory.grpc.v1.AdminMemoryItem> 
      getItemsList();
  /**
   * <code>repeated .memory.v1.AdminMemoryItem items = 1;</code>
   */
  io.github.chirino.memory.grpc.v1.AdminMemoryItem getItems(int index);
  /**
   * <code>repeated .memory.v1.AdminMemoryItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .memory.v1.AdminMemoryItem items = 1;</code>
   */
  java.util.List<? extends io.github.chirino.memory.grpc.v1.AdminMemoryItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .memory.v1.AdminMemoryItem items = 1;</code>
   */
  io.github.chirino.memory.grpc.v1.AdminMemoryItemOrBuilder getItemsOrBuilder(
      int index);
}
