// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminListChildConversationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminListChildConversationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .memory.v1.AdminChildConversationSummary children = 1;</code>
   */
  java.util.List<io.github.chirino.memory.grpc.v1.AdminChildConversationSummary> 
      getChildrenList();
  /**
   * <code>repeated .memory.v1.AdminChildConversationSummary children = 1;</code>
   */
  io.github.chirino.memory.grpc.v1.AdminChildConversationSummary getChildren(int index);
  /**
   * <code>repeated .memory.v1.AdminChildConversationSummary children = 1;</code>
   */
  int getChildrenCount();
  /**
   * <code>repeated .memory.v1.AdminChildConversationSummary children = 1;</code>
   */
  java.util.List<? extends io.github.chirino.memory.grpc.v1.AdminChildConversationSummaryOrBuilder> 
      getChildrenOrBuilderList();
  /**
   * <code>repeated .memory.v1.AdminChildConversationSummary children = 1;</code>
   */
  io.github.chirino.memory.grpc.v1.AdminChildConversationSummaryOrBuilder getChildrenOrBuilder(
      int index);

  /**
   * <code>.memory.v1.PageInfo page_info = 2;</code>
   * @return Whether the pageInfo field is set.
   */
  boolean hasPageInfo();
  /**
   * <code>.memory.v1.PageInfo page_info = 2;</code>
   * @return The pageInfo.
   */
  io.github.chirino.memory.grpc.v1.PageInfo getPageInfo();
  /**
   * <code>.memory.v1.PageInfo page_info = 2;</code>
   */
  io.github.chirino.memory.grpc.v1.PageInfoOrBuilder getPageInfoOrBuilder();
}
