// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminListEntriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminListEntriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Conversation identifier
   * </pre>
   *
   * <code>string conversation_id = 1;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <pre>
   * Conversation identifier
   * </pre>
   *
   * <code>string conversation_id = 1;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <code>.memory.v1.Channel channel = 2;</code>
   * @return The enum numeric value on the wire for channel.
   */
  int getChannelValue();
  /**
   * <code>.memory.v1.Channel channel = 2;</code>
   * @return The channel.
   */
  io.github.chirino.memory.grpc.v1.Channel getChannel();

  /**
   * <code>string epoch_filter = 3;</code>
   * @return The epochFilter.
   */
  java.lang.String getEpochFilter();
  /**
   * <code>string epoch_filter = 3;</code>
   * @return The bytes for epochFilter.
   */
  com.google.protobuf.ByteString
      getEpochFilterBytes();

  /**
   * <code>.memory.v1.PageRequest page = 4;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.memory.v1.PageRequest page = 4;</code>
   * @return The page.
   */
  io.github.chirino.memory.grpc.v1.PageRequest getPage();
  /**
   * <code>.memory.v1.PageRequest page = 4;</code>
   */
  io.github.chirino.memory.grpc.v1.PageRequestOrBuilder getPageOrBuilder();

  /**
   * <pre>
   * Controls which fork entries to include: "none" (default) follows ancestry,
   * "all" returns entries from all forks in the conversation group
   * </pre>
   *
   * <code>string forks = 5;</code>
   * @return The forks.
   */
  java.lang.String getForks();
  /**
   * <pre>
   * Controls which fork entries to include: "none" (default) follows ancestry,
   * "all" returns entries from all forks in the conversation group
   * </pre>
   *
   * <code>string forks = 5;</code>
   * @return The bytes for forks.
   */
  com.google.protobuf.ByteString
      getForksBytes();

  /**
   * <pre>
   * Return entries at or before this entry in the admin-visible conversation order.
   * </pre>
   *
   * <code>optional bytes up_to_entry_id = 6;</code>
   * @return Whether the upToEntryId field is set.
   */
  boolean hasUpToEntryId();
  /**
   * <pre>
   * Return entries at or before this entry in the admin-visible conversation order.
   * </pre>
   *
   * <code>optional bytes up_to_entry_id = 6;</code>
   * @return The upToEntryId.
   */
  com.google.protobuf.ByteString getUpToEntryId();
}
