// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.AdminGetMemoryIndexStatusRequest}
 */
public final class AdminGetMemoryIndexStatusRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.AdminGetMemoryIndexStatusRequest)
    AdminGetMemoryIndexStatusRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdminGetMemoryIndexStatusRequest.newBuilder() to construct.
  private AdminGetMemoryIndexStatusRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdminGetMemoryIndexStatusRequest() {
    justification_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdminGetMemoryIndexStatusRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminGetMemoryIndexStatusRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminGetMemoryIndexStatusRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.class, io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.Builder.class);
  }

  private int bitField0_;
  public static final int JUSTIFICATION_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object justification_ = "";
  /**
   * <code>optional string justification = 1;</code>
   * @return Whether the justification field is set.
   */
  @java.lang.Override
  public boolean hasJustification() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string justification = 1;</code>
   * @return The justification.
   */
  @java.lang.Override
  public java.lang.String getJustification() {
    java.lang.Object ref = justification_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      justification_ = s;
      return s;
    }
  }
  /**
   * <code>optional string justification = 1;</code>
   * @return The bytes for justification.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJustificationBytes() {
    java.lang.Object ref = justification_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      justification_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, justification_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, justification_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest other = (io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest) obj;

    if (hasJustification() != other.hasJustification()) return false;
    if (hasJustification()) {
      if (!getJustification()
          .equals(other.getJustification())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasJustification()) {
      hash = (37 * hash) + JUSTIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getJustification().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.AdminGetMemoryIndexStatusRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.AdminGetMemoryIndexStatusRequest)
      io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminGetMemoryIndexStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminGetMemoryIndexStatusRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.class, io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      justification_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminGetMemoryIndexStatusRequest_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest build() {
      io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest buildPartial() {
      io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest result = new io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.justification_ = justification_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest other) {
      if (other == io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest.getDefaultInstance()) return this;
      if (other.hasJustification()) {
        justification_ = other.justification_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              justification_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object justification_ = "";
    /**
     * <code>optional string justification = 1;</code>
     * @return Whether the justification field is set.
     */
    public boolean hasJustification() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string justification = 1;</code>
     * @return The justification.
     */
    public java.lang.String getJustification() {
      java.lang.Object ref = justification_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        justification_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string justification = 1;</code>
     * @return The bytes for justification.
     */
    public com.google.protobuf.ByteString
        getJustificationBytes() {
      java.lang.Object ref = justification_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        justification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string justification = 1;</code>
     * @param value The justification to set.
     * @return This builder for chaining.
     */
    public Builder setJustification(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      justification_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional string justification = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearJustification() {
      justification_ = getDefaultInstance().getJustification();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>optional string justification = 1;</code>
     * @param value The bytes for justification to set.
     * @return This builder for chaining.
     */
    public Builder setJustificationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      justification_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.AdminGetMemoryIndexStatusRequest)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.AdminGetMemoryIndexStatusRequest)
  private static final io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest();
  }

  public static io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminGetMemoryIndexStatusRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdminGetMemoryIndexStatusRequest>() {
    @java.lang.Override
    public AdminGetMemoryIndexStatusRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminGetMemoryIndexStatusRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminGetMemoryIndexStatusRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.AdminGetMemoryIndexStatusRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

