// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.AdminSearchMemoriesRequest}
 */
public final class AdminSearchMemoriesRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.AdminSearchMemoriesRequest)
    AdminSearchMemoriesRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdminSearchMemoriesRequest.newBuilder() to construct.
  private AdminSearchMemoriesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdminSearchMemoriesRequest() {
    namespacePrefix_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    keyPrefix_ = "";
    query_ = "";
    archived_ = 0;
    justification_ = "";
    asUserId_ = "";
    queries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdminSearchMemoriesRequest();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminSearchMemoriesRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminSearchMemoriesRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.class, io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.Builder.class);
  }

  private int bitField0_;
  public static final int NAMESPACE_PREFIX_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList namespacePrefix_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return A list containing the namespacePrefix.
   */
  public com.google.protobuf.ProtocolStringList
      getNamespacePrefixList() {
    return namespacePrefix_;
  }
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return The count of namespacePrefix.
   */
  public int getNamespacePrefixCount() {
    return namespacePrefix_.size();
  }
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the element to return.
   * @return The namespacePrefix at the given index.
   */
  public java.lang.String getNamespacePrefix(int index) {
    return namespacePrefix_.get(index);
  }
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the namespacePrefix at the given index.
   */
  public com.google.protobuf.ByteString
      getNamespacePrefixBytes(int index) {
    return namespacePrefix_.getByteString(index);
  }

  public static final int KEY_PREFIX_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object keyPrefix_ = "";
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return Whether the keyPrefix field is set.
   */
  @java.lang.Override
  public boolean hasKeyPrefix() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The keyPrefix.
   */
  @java.lang.Override
  public java.lang.String getKeyPrefix() {
    java.lang.Object ref = keyPrefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      keyPrefix_ = s;
      return s;
    }
  }
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The bytes for keyPrefix.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getKeyPrefixBytes() {
    java.lang.Object ref = keyPrefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      keyPrefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object query_ = "";
  /**
   * <code>string query = 3;</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      query_ = s;
      return s;
    }
  }
  /**
   * <code>string query = 3;</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    java.lang.Object ref = query_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      query_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FILTER_FIELD_NUMBER = 4;
  private com.google.protobuf.Struct filter_;
  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   * @return Whether the filter field is set.
   */
  @java.lang.Override
  public boolean hasFilter() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   * @return The filter.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getFilter() {
    return filter_ == null ? com.google.protobuf.Struct.getDefaultInstance() : filter_;
  }
  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getFilterOrBuilder() {
    return filter_ == null ? com.google.protobuf.Struct.getDefaultInstance() : filter_;
  }

  public static final int ARCHIVED_FIELD_NUMBER = 5;
  private int archived_ = 0;
  /**
   * <code>.memory.v1.ArchiveFilter archived = 5;</code>
   * @return The enum numeric value on the wire for archived.
   */
  @java.lang.Override public int getArchivedValue() {
    return archived_;
  }
  /**
   * <code>.memory.v1.ArchiveFilter archived = 5;</code>
   * @return The archived.
   */
  @java.lang.Override public io.github.chirino.memory.grpc.v1.ArchiveFilter getArchived() {
    io.github.chirino.memory.grpc.v1.ArchiveFilter result = io.github.chirino.memory.grpc.v1.ArchiveFilter.forNumber(archived_);
    return result == null ? io.github.chirino.memory.grpc.v1.ArchiveFilter.UNRECOGNIZED : result;
  }

  public static final int INCLUDE_USAGE_FIELD_NUMBER = 6;
  private boolean includeUsage_ = false;
  /**
   * <code>bool include_usage = 6;</code>
   * @return The includeUsage.
   */
  @java.lang.Override
  public boolean getIncludeUsage() {
    return includeUsage_;
  }

  public static final int LIMIT_FIELD_NUMBER = 7;
  private int limit_ = 0;
  /**
   * <code>int32 limit = 7;</code>
   * @return The limit.
   */
  @java.lang.Override
  public int getLimit() {
    return limit_;
  }

  public static final int JUSTIFICATION_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object justification_ = "";
  /**
   * <code>optional string justification = 8;</code>
   * @return Whether the justification field is set.
   */
  @java.lang.Override
  public boolean hasJustification() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string justification = 8;</code>
   * @return The justification.
   */
  @java.lang.Override
  public java.lang.String getJustification() {
    java.lang.Object ref = justification_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      justification_ = s;
      return s;
    }
  }
  /**
   * <code>optional string justification = 8;</code>
   * @return The bytes for justification.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getJustificationBytes() {
    java.lang.Object ref = justification_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      justification_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AS_USER_ID_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private volatile java.lang.Object asUserId_ = "";
  /**
   * <code>optional string as_user_id = 9;</code>
   * @return Whether the asUserId field is set.
   */
  @java.lang.Override
  public boolean hasAsUserId() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string as_user_id = 9;</code>
   * @return The asUserId.
   */
  @java.lang.Override
  public java.lang.String getAsUserId() {
    java.lang.Object ref = asUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      asUserId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string as_user_id = 9;</code>
   * @return The bytes for asUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAsUserIdBytes() {
    java.lang.Object ref = asUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      asUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int QUERIES_FIELD_NUMBER = 10;
  @SuppressWarnings("serial")
  private java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery> queries_;
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery> getQueriesList() {
    return queries_;
  }
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder> 
      getQueriesOrBuilderList() {
    return queries_;
  }
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  @java.lang.Override
  public int getQueriesCount() {
    return queries_.size();
  }
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.MemorySearchQuery getQueries(int index) {
    return queries_.get(index);
  }
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder getQueriesOrBuilder(
      int index) {
    return queries_.get(index);
  }

  public static final int PER_QUERY_LIMIT_FIELD_NUMBER = 11;
  private int perQueryLimit_ = 0;
  /**
   * <code>int32 per_query_limit = 11;</code>
   * @return The perQueryLimit.
   */
  @java.lang.Override
  public int getPerQueryLimit() {
    return perQueryLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < namespacePrefix_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, namespacePrefix_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, keyPrefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, query_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getFilter());
    }
    if (archived_ != io.github.chirino.memory.grpc.v1.ArchiveFilter.ARCHIVE_FILTER_UNSPECIFIED.getNumber()) {
      output.writeEnum(5, archived_);
    }
    if (includeUsage_ != false) {
      output.writeBool(6, includeUsage_);
    }
    if (limit_ != 0) {
      output.writeInt32(7, limit_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, justification_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, asUserId_);
    }
    for (int i = 0; i < queries_.size(); i++) {
      output.writeMessage(10, queries_.get(i));
    }
    if (perQueryLimit_ != 0) {
      output.writeInt32(11, perQueryLimit_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < namespacePrefix_.size(); i++) {
        dataSize += computeStringSizeNoTag(namespacePrefix_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNamespacePrefixList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, keyPrefix_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(query_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, query_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getFilter());
    }
    if (archived_ != io.github.chirino.memory.grpc.v1.ArchiveFilter.ARCHIVE_FILTER_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, archived_);
    }
    if (includeUsage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, includeUsage_);
    }
    if (limit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, limit_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, justification_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, asUserId_);
    }
    for (int i = 0; i < queries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(10, queries_.get(i));
    }
    if (perQueryLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, perQueryLimit_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest other = (io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest) obj;

    if (!getNamespacePrefixList()
        .equals(other.getNamespacePrefixList())) return false;
    if (hasKeyPrefix() != other.hasKeyPrefix()) return false;
    if (hasKeyPrefix()) {
      if (!getKeyPrefix()
          .equals(other.getKeyPrefix())) return false;
    }
    if (!getQuery()
        .equals(other.getQuery())) return false;
    if (hasFilter() != other.hasFilter()) return false;
    if (hasFilter()) {
      if (!getFilter()
          .equals(other.getFilter())) return false;
    }
    if (archived_ != other.archived_) return false;
    if (getIncludeUsage()
        != other.getIncludeUsage()) return false;
    if (getLimit()
        != other.getLimit()) return false;
    if (hasJustification() != other.hasJustification()) return false;
    if (hasJustification()) {
      if (!getJustification()
          .equals(other.getJustification())) return false;
    }
    if (hasAsUserId() != other.hasAsUserId()) return false;
    if (hasAsUserId()) {
      if (!getAsUserId()
          .equals(other.getAsUserId())) return false;
    }
    if (!getQueriesList()
        .equals(other.getQueriesList())) return false;
    if (getPerQueryLimit()
        != other.getPerQueryLimit()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNamespacePrefixCount() > 0) {
      hash = (37 * hash) + NAMESPACE_PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getNamespacePrefixList().hashCode();
    }
    if (hasKeyPrefix()) {
      hash = (37 * hash) + KEY_PREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getKeyPrefix().hashCode();
    }
    hash = (37 * hash) + QUERY_FIELD_NUMBER;
    hash = (53 * hash) + getQuery().hashCode();
    if (hasFilter()) {
      hash = (37 * hash) + FILTER_FIELD_NUMBER;
      hash = (53 * hash) + getFilter().hashCode();
    }
    hash = (37 * hash) + ARCHIVED_FIELD_NUMBER;
    hash = (53 * hash) + archived_;
    hash = (37 * hash) + INCLUDE_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIncludeUsage());
    hash = (37 * hash) + LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getLimit();
    if (hasJustification()) {
      hash = (37 * hash) + JUSTIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getJustification().hashCode();
    }
    if (hasAsUserId()) {
      hash = (37 * hash) + AS_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAsUserId().hashCode();
    }
    if (getQueriesCount() > 0) {
      hash = (37 * hash) + QUERIES_FIELD_NUMBER;
      hash = (53 * hash) + getQueriesList().hashCode();
    }
    hash = (37 * hash) + PER_QUERY_LIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getPerQueryLimit();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.AdminSearchMemoriesRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.AdminSearchMemoriesRequest)
      io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminSearchMemoriesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminSearchMemoriesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.class, io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFilterFieldBuilder();
        getQueriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      namespacePrefix_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      keyPrefix_ = "";
      query_ = "";
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      archived_ = 0;
      includeUsage_ = false;
      limit_ = 0;
      justification_ = "";
      asUserId_ = "";
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
      } else {
        queries_ = null;
        queriesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000200);
      perQueryLimit_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminSearchMemoriesRequest_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest build() {
      io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest buildPartial() {
      io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest result = new io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest result) {
      if (queriesBuilder_ == null) {
        if (((bitField0_ & 0x00000200) != 0)) {
          queries_ = java.util.Collections.unmodifiableList(queries_);
          bitField0_ = (bitField0_ & ~0x00000200);
        }
        result.queries_ = queries_;
      } else {
        result.queries_ = queriesBuilder_.build();
      }
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        namespacePrefix_.makeImmutable();
        result.namespacePrefix_ = namespacePrefix_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.keyPrefix_ = keyPrefix_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.query_ = query_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.filter_ = filterBuilder_ == null
            ? filter_
            : filterBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.archived_ = archived_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.includeUsage_ = includeUsage_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.limit_ = limit_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.justification_ = justification_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.asUserId_ = asUserId_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.perQueryLimit_ = perQueryLimit_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest other) {
      if (other == io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest.getDefaultInstance()) return this;
      if (!other.namespacePrefix_.isEmpty()) {
        if (namespacePrefix_.isEmpty()) {
          namespacePrefix_ = other.namespacePrefix_;
          bitField0_ |= 0x00000001;
        } else {
          ensureNamespacePrefixIsMutable();
          namespacePrefix_.addAll(other.namespacePrefix_);
        }
        onChanged();
      }
      if (other.hasKeyPrefix()) {
        keyPrefix_ = other.keyPrefix_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getQuery().isEmpty()) {
        query_ = other.query_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasFilter()) {
        mergeFilter(other.getFilter());
      }
      if (other.archived_ != 0) {
        setArchivedValue(other.getArchivedValue());
      }
      if (other.getIncludeUsage() != false) {
        setIncludeUsage(other.getIncludeUsage());
      }
      if (other.getLimit() != 0) {
        setLimit(other.getLimit());
      }
      if (other.hasJustification()) {
        justification_ = other.justification_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.hasAsUserId()) {
        asUserId_ = other.asUserId_;
        bitField0_ |= 0x00000100;
        onChanged();
      }
      if (queriesBuilder_ == null) {
        if (!other.queries_.isEmpty()) {
          if (queries_.isEmpty()) {
            queries_ = other.queries_;
            bitField0_ = (bitField0_ & ~0x00000200);
          } else {
            ensureQueriesIsMutable();
            queries_.addAll(other.queries_);
          }
          onChanged();
        }
      } else {
        if (!other.queries_.isEmpty()) {
          if (queriesBuilder_.isEmpty()) {
            queriesBuilder_.dispose();
            queriesBuilder_ = null;
            queries_ = other.queries_;
            bitField0_ = (bitField0_ & ~0x00000200);
            queriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getQueriesFieldBuilder() : null;
          } else {
            queriesBuilder_.addAllMessages(other.queries_);
          }
        }
      }
      if (other.getPerQueryLimit() != 0) {
        setPerQueryLimit(other.getPerQueryLimit());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureNamespacePrefixIsMutable();
              namespacePrefix_.add(s);
              break;
            } // case 10
            case 18: {
              keyPrefix_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              query_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getFilterFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              archived_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              includeUsage_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              limit_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              justification_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              asUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 82: {
              io.github.chirino.memory.grpc.v1.MemorySearchQuery m =
                  input.readMessage(
                      io.github.chirino.memory.grpc.v1.MemorySearchQuery.parser(),
                      extensionRegistry);
              if (queriesBuilder_ == null) {
                ensureQueriesIsMutable();
                queries_.add(m);
              } else {
                queriesBuilder_.addMessage(m);
              }
              break;
            } // case 82
            case 88: {
              perQueryLimit_ = input.readInt32();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList namespacePrefix_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureNamespacePrefixIsMutable() {
      if (!namespacePrefix_.isModifiable()) {
        namespacePrefix_ = new com.google.protobuf.LazyStringArrayList(namespacePrefix_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @return A list containing the namespacePrefix.
     */
    public com.google.protobuf.ProtocolStringList
        getNamespacePrefixList() {
      namespacePrefix_.makeImmutable();
      return namespacePrefix_;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @return The count of namespacePrefix.
     */
    public int getNamespacePrefixCount() {
      return namespacePrefix_.size();
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param index The index of the element to return.
     * @return The namespacePrefix at the given index.
     */
    public java.lang.String getNamespacePrefix(int index) {
      return namespacePrefix_.get(index);
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the namespacePrefix at the given index.
     */
    public com.google.protobuf.ByteString
        getNamespacePrefixBytes(int index) {
      return namespacePrefix_.getByteString(index);
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param index The index to set the value at.
     * @param value The namespacePrefix to set.
     * @return This builder for chaining.
     */
    public Builder setNamespacePrefix(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNamespacePrefixIsMutable();
      namespacePrefix_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param value The namespacePrefix to add.
     * @return This builder for chaining.
     */
    public Builder addNamespacePrefix(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureNamespacePrefixIsMutable();
      namespacePrefix_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param values The namespacePrefix to add.
     * @return This builder for chaining.
     */
    public Builder addAllNamespacePrefix(
        java.lang.Iterable<java.lang.String> values) {
      ensureNamespacePrefixIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, namespacePrefix_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespacePrefix() {
      namespacePrefix_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string namespace_prefix = 1;</code>
     * @param value The bytes of the namespacePrefix to add.
     * @return This builder for chaining.
     */
    public Builder addNamespacePrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureNamespacePrefixIsMutable();
      namespacePrefix_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object keyPrefix_ = "";
    /**
     * <code>optional string key_prefix = 2;</code>
     * @return Whether the keyPrefix field is set.
     */
    public boolean hasKeyPrefix() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string key_prefix = 2;</code>
     * @return The keyPrefix.
     */
    public java.lang.String getKeyPrefix() {
      java.lang.Object ref = keyPrefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        keyPrefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string key_prefix = 2;</code>
     * @return The bytes for keyPrefix.
     */
    public com.google.protobuf.ByteString
        getKeyPrefixBytes() {
      java.lang.Object ref = keyPrefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        keyPrefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string key_prefix = 2;</code>
     * @param value The keyPrefix to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPrefix(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      keyPrefix_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string key_prefix = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKeyPrefix() {
      keyPrefix_ = getDefaultInstance().getKeyPrefix();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string key_prefix = 2;</code>
     * @param value The bytes for keyPrefix to set.
     * @return This builder for chaining.
     */
    public Builder setKeyPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      keyPrefix_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object query_ = "";
    /**
     * <code>string query = 3;</code>
     * @return The query.
     */
    public java.lang.String getQuery() {
      java.lang.Object ref = query_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        query_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string query = 3;</code>
     * @return The bytes for query.
     */
    public com.google.protobuf.ByteString
        getQueryBytes() {
      java.lang.Object ref = query_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        query_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string query = 3;</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      query_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string query = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      query_ = getDefaultInstance().getQuery();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string query = 3;</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      query_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct filter_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> filterBuilder_;
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     * @return Whether the filter field is set.
     */
    public boolean hasFilter() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     * @return The filter.
     */
    public com.google.protobuf.Struct getFilter() {
      if (filterBuilder_ == null) {
        return filter_ == null ? com.google.protobuf.Struct.getDefaultInstance() : filter_;
      } else {
        return filterBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public Builder setFilter(com.google.protobuf.Struct value) {
      if (filterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        filter_ = value;
      } else {
        filterBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public Builder setFilter(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (filterBuilder_ == null) {
        filter_ = builderForValue.build();
      } else {
        filterBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public Builder mergeFilter(com.google.protobuf.Struct value) {
      if (filterBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          filter_ != null &&
          filter_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getFilterBuilder().mergeFrom(value);
        } else {
          filter_ = value;
        }
      } else {
        filterBuilder_.mergeFrom(value);
      }
      if (filter_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public Builder clearFilter() {
      bitField0_ = (bitField0_ & ~0x00000008);
      filter_ = null;
      if (filterBuilder_ != null) {
        filterBuilder_.dispose();
        filterBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public com.google.protobuf.Struct.Builder getFilterBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getFilterFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    public com.google.protobuf.StructOrBuilder getFilterOrBuilder() {
      if (filterBuilder_ != null) {
        return filterBuilder_.getMessageOrBuilder();
      } else {
        return filter_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : filter_;
      }
    }
    /**
     * <code>optional .google.protobuf.Struct filter = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getFilterFieldBuilder() {
      if (filterBuilder_ == null) {
        filterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getFilter(),
                getParentForChildren(),
                isClean());
        filter_ = null;
      }
      return filterBuilder_;
    }

    private int archived_ = 0;
    /**
     * <code>.memory.v1.ArchiveFilter archived = 5;</code>
     * @return The enum numeric value on the wire for archived.
     */
    @java.lang.Override public int getArchivedValue() {
      return archived_;
    }
    /**
     * <code>.memory.v1.ArchiveFilter archived = 5;</code>
     * @param value The enum numeric value on the wire for archived to set.
     * @return This builder for chaining.
     */
    public Builder setArchivedValue(int value) {
      archived_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.memory.v1.ArchiveFilter archived = 5;</code>
     * @return The archived.
     */
    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.ArchiveFilter getArchived() {
      io.github.chirino.memory.grpc.v1.ArchiveFilter result = io.github.chirino.memory.grpc.v1.ArchiveFilter.forNumber(archived_);
      return result == null ? io.github.chirino.memory.grpc.v1.ArchiveFilter.UNRECOGNIZED : result;
    }
    /**
     * <code>.memory.v1.ArchiveFilter archived = 5;</code>
     * @param value The archived to set.
     * @return This builder for chaining.
     */
    public Builder setArchived(io.github.chirino.memory.grpc.v1.ArchiveFilter value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      archived_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.memory.v1.ArchiveFilter archived = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArchived() {
      bitField0_ = (bitField0_ & ~0x00000010);
      archived_ = 0;
      onChanged();
      return this;
    }

    private boolean includeUsage_ ;
    /**
     * <code>bool include_usage = 6;</code>
     * @return The includeUsage.
     */
    @java.lang.Override
    public boolean getIncludeUsage() {
      return includeUsage_;
    }
    /**
     * <code>bool include_usage = 6;</code>
     * @param value The includeUsage to set.
     * @return This builder for chaining.
     */
    public Builder setIncludeUsage(boolean value) {

      includeUsage_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool include_usage = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncludeUsage() {
      bitField0_ = (bitField0_ & ~0x00000020);
      includeUsage_ = false;
      onChanged();
      return this;
    }

    private int limit_ ;
    /**
     * <code>int32 limit = 7;</code>
     * @return The limit.
     */
    @java.lang.Override
    public int getLimit() {
      return limit_;
    }
    /**
     * <code>int32 limit = 7;</code>
     * @param value The limit to set.
     * @return This builder for chaining.
     */
    public Builder setLimit(int value) {

      limit_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 limit = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimit() {
      bitField0_ = (bitField0_ & ~0x00000040);
      limit_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object justification_ = "";
    /**
     * <code>optional string justification = 8;</code>
     * @return Whether the justification field is set.
     */
    public boolean hasJustification() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional string justification = 8;</code>
     * @return The justification.
     */
    public java.lang.String getJustification() {
      java.lang.Object ref = justification_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        justification_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string justification = 8;</code>
     * @return The bytes for justification.
     */
    public com.google.protobuf.ByteString
        getJustificationBytes() {
      java.lang.Object ref = justification_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        justification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string justification = 8;</code>
     * @param value The justification to set.
     * @return This builder for chaining.
     */
    public Builder setJustification(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      justification_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional string justification = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearJustification() {
      justification_ = getDefaultInstance().getJustification();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>optional string justification = 8;</code>
     * @param value The bytes for justification to set.
     * @return This builder for chaining.
     */
    public Builder setJustificationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      justification_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private java.lang.Object asUserId_ = "";
    /**
     * <code>optional string as_user_id = 9;</code>
     * @return Whether the asUserId field is set.
     */
    public boolean hasAsUserId() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string as_user_id = 9;</code>
     * @return The asUserId.
     */
    public java.lang.String getAsUserId() {
      java.lang.Object ref = asUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        asUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string as_user_id = 9;</code>
     * @return The bytes for asUserId.
     */
    public com.google.protobuf.ByteString
        getAsUserIdBytes() {
      java.lang.Object ref = asUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        asUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string as_user_id = 9;</code>
     * @param value The asUserId to set.
     * @return This builder for chaining.
     */
    public Builder setAsUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      asUserId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional string as_user_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearAsUserId() {
      asUserId_ = getDefaultInstance().getAsUserId();
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <code>optional string as_user_id = 9;</code>
     * @param value The bytes for asUserId to set.
     * @return This builder for chaining.
     */
    public Builder setAsUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      asUserId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }

    private java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery> queries_ =
      java.util.Collections.emptyList();
    private void ensureQueriesIsMutable() {
      if (!((bitField0_ & 0x00000200) != 0)) {
        queries_ = new java.util.ArrayList<io.github.chirino.memory.grpc.v1.MemorySearchQuery>(queries_);
        bitField0_ |= 0x00000200;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.chirino.memory.grpc.v1.MemorySearchQuery, io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder, io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder> queriesBuilder_;

    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery> getQueriesList() {
      if (queriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(queries_);
      } else {
        return queriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public int getQueriesCount() {
      if (queriesBuilder_ == null) {
        return queries_.size();
      } else {
        return queriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemorySearchQuery getQueries(int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);
      } else {
        return queriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder setQueries(
        int index, io.github.chirino.memory.grpc.v1.MemorySearchQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.set(index, value);
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder setQueries(
        int index, io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.set(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder addQueries(io.github.chirino.memory.grpc.v1.MemorySearchQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder addQueries(
        int index, io.github.chirino.memory.grpc.v1.MemorySearchQuery value) {
      if (queriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureQueriesIsMutable();
        queries_.add(index, value);
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder addQueries(
        io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder addQueries(
        int index, io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder builderForValue) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.add(index, builderForValue.build());
        onChanged();
      } else {
        queriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder addAllQueries(
        java.lang.Iterable<? extends io.github.chirino.memory.grpc.v1.MemorySearchQuery> values) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, queries_);
        onChanged();
      } else {
        queriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder clearQueries() {
      if (queriesBuilder_ == null) {
        queries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);
        onChanged();
      } else {
        queriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public Builder removeQueries(int index) {
      if (queriesBuilder_ == null) {
        ensureQueriesIsMutable();
        queries_.remove(index);
        onChanged();
      } else {
        queriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder getQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder getQueriesOrBuilder(
        int index) {
      if (queriesBuilder_ == null) {
        return queries_.get(index);  } else {
        return queriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public java.util.List<? extends io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder> 
         getQueriesOrBuilderList() {
      if (queriesBuilder_ != null) {
        return queriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(queries_);
      }
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder addQueriesBuilder() {
      return getQueriesFieldBuilder().addBuilder(
          io.github.chirino.memory.grpc.v1.MemorySearchQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder addQueriesBuilder(
        int index) {
      return getQueriesFieldBuilder().addBuilder(
          index, io.github.chirino.memory.grpc.v1.MemorySearchQuery.getDefaultInstance());
    }
    /**
     * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
     */
    public java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder> 
         getQueriesBuilderList() {
      return getQueriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.chirino.memory.grpc.v1.MemorySearchQuery, io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder, io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder> 
        getQueriesFieldBuilder() {
      if (queriesBuilder_ == null) {
        queriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.chirino.memory.grpc.v1.MemorySearchQuery, io.github.chirino.memory.grpc.v1.MemorySearchQuery.Builder, io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder>(
                queries_,
                ((bitField0_ & 0x00000200) != 0),
                getParentForChildren(),
                isClean());
        queries_ = null;
      }
      return queriesBuilder_;
    }

    private int perQueryLimit_ ;
    /**
     * <code>int32 per_query_limit = 11;</code>
     * @return The perQueryLimit.
     */
    @java.lang.Override
    public int getPerQueryLimit() {
      return perQueryLimit_;
    }
    /**
     * <code>int32 per_query_limit = 11;</code>
     * @param value The perQueryLimit to set.
     * @return This builder for chaining.
     */
    public Builder setPerQueryLimit(int value) {

      perQueryLimit_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>int32 per_query_limit = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearPerQueryLimit() {
      bitField0_ = (bitField0_ & ~0x00000400);
      perQueryLimit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.AdminSearchMemoriesRequest)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.AdminSearchMemoriesRequest)
  private static final io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest();
  }

  public static io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminSearchMemoriesRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdminSearchMemoriesRequest>() {
    @java.lang.Override
    public AdminSearchMemoriesRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminSearchMemoriesRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminSearchMemoriesRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.AdminSearchMemoriesRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

