// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.AdminListMemoryNamespacesResponse}
 */
public final class AdminListMemoryNamespacesResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.AdminListMemoryNamespacesResponse)
    AdminListMemoryNamespacesResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdminListMemoryNamespacesResponse.newBuilder() to construct.
  private AdminListMemoryNamespacesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdminListMemoryNamespacesResponse() {
    namespaces_ = java.util.Collections.emptyList();
    afterCursor_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdminListMemoryNamespacesResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminListMemoryNamespacesResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminListMemoryNamespacesResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.class, io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.Builder.class);
  }

  private int bitField0_;
  public static final int NAMESPACES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.chirino.memory.grpc.v1.MemoryNamespace> namespaces_;
  /**
   * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.github.chirino.memory.grpc.v1.MemoryNamespace> getNamespacesList() {
    return namespaces_;
  }
  /**
   * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder> 
      getNamespacesOrBuilderList() {
    return namespaces_;
  }
  /**
   * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
   */
  @java.lang.Override
  public int getNamespacesCount() {
    return namespaces_.size();
  }
  /**
   * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
   */
  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.MemoryNamespace getNamespaces(int index) {
    return namespaces_.get(index);
  }
  /**
   * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
   */
  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder getNamespacesOrBuilder(
      int index) {
    return namespaces_.get(index);
  }

  public static final int AFTER_CURSOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object afterCursor_ = "";
  /**
   * <code>optional string after_cursor = 2;</code>
   * @return Whether the afterCursor field is set.
   */
  @java.lang.Override
  public boolean hasAfterCursor() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string after_cursor = 2;</code>
   * @return The afterCursor.
   */
  @java.lang.Override
  public java.lang.String getAfterCursor() {
    java.lang.Object ref = afterCursor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      afterCursor_ = s;
      return s;
    }
  }
  /**
   * <code>optional string after_cursor = 2;</code>
   * @return The bytes for afterCursor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAfterCursorBytes() {
    java.lang.Object ref = afterCursor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      afterCursor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < namespaces_.size(); i++) {
      output.writeMessage(1, namespaces_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, afterCursor_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < namespaces_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, namespaces_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, afterCursor_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse other = (io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse) obj;

    if (!getNamespacesList()
        .equals(other.getNamespacesList())) return false;
    if (hasAfterCursor() != other.hasAfterCursor()) return false;
    if (hasAfterCursor()) {
      if (!getAfterCursor()
          .equals(other.getAfterCursor())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNamespacesCount() > 0) {
      hash = (37 * hash) + NAMESPACES_FIELD_NUMBER;
      hash = (53 * hash) + getNamespacesList().hashCode();
    }
    if (hasAfterCursor()) {
      hash = (37 * hash) + AFTER_CURSOR_FIELD_NUMBER;
      hash = (53 * hash) + getAfterCursor().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.AdminListMemoryNamespacesResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.AdminListMemoryNamespacesResponse)
      io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminListMemoryNamespacesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminListMemoryNamespacesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.class, io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (namespacesBuilder_ == null) {
        namespaces_ = java.util.Collections.emptyList();
      } else {
        namespaces_ = null;
        namespacesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      afterCursor_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminListMemoryNamespacesResponse_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse build() {
      io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse buildPartial() {
      io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse result = new io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse result) {
      if (namespacesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          namespaces_ = java.util.Collections.unmodifiableList(namespaces_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.namespaces_ = namespaces_;
      } else {
        result.namespaces_ = namespacesBuilder_.build();
      }
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.afterCursor_ = afterCursor_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse other) {
      if (other == io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse.getDefaultInstance()) return this;
      if (namespacesBuilder_ == null) {
        if (!other.namespaces_.isEmpty()) {
          if (namespaces_.isEmpty()) {
            namespaces_ = other.namespaces_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNamespacesIsMutable();
            namespaces_.addAll(other.namespaces_);
          }
          onChanged();
        }
      } else {
        if (!other.namespaces_.isEmpty()) {
          if (namespacesBuilder_.isEmpty()) {
            namespacesBuilder_.dispose();
            namespacesBuilder_ = null;
            namespaces_ = other.namespaces_;
            bitField0_ = (bitField0_ & ~0x00000001);
            namespacesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNamespacesFieldBuilder() : null;
          } else {
            namespacesBuilder_.addAllMessages(other.namespaces_);
          }
        }
      }
      if (other.hasAfterCursor()) {
        afterCursor_ = other.afterCursor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.chirino.memory.grpc.v1.MemoryNamespace m =
                  input.readMessage(
                      io.github.chirino.memory.grpc.v1.MemoryNamespace.parser(),
                      extensionRegistry);
              if (namespacesBuilder_ == null) {
                ensureNamespacesIsMutable();
                namespaces_.add(m);
              } else {
                namespacesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              afterCursor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.chirino.memory.grpc.v1.MemoryNamespace> namespaces_ =
      java.util.Collections.emptyList();
    private void ensureNamespacesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        namespaces_ = new java.util.ArrayList<io.github.chirino.memory.grpc.v1.MemoryNamespace>(namespaces_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.chirino.memory.grpc.v1.MemoryNamespace, io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder, io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder> namespacesBuilder_;

    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public java.util.List<io.github.chirino.memory.grpc.v1.MemoryNamespace> getNamespacesList() {
      if (namespacesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(namespaces_);
      } else {
        return namespacesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public int getNamespacesCount() {
      if (namespacesBuilder_ == null) {
        return namespaces_.size();
      } else {
        return namespacesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemoryNamespace getNamespaces(int index) {
      if (namespacesBuilder_ == null) {
        return namespaces_.get(index);
      } else {
        return namespacesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder setNamespaces(
        int index, io.github.chirino.memory.grpc.v1.MemoryNamespace value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.set(index, value);
        onChanged();
      } else {
        namespacesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder setNamespaces(
        int index, io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.set(index, builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder addNamespaces(io.github.chirino.memory.grpc.v1.MemoryNamespace value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.add(value);
        onChanged();
      } else {
        namespacesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder addNamespaces(
        int index, io.github.chirino.memory.grpc.v1.MemoryNamespace value) {
      if (namespacesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNamespacesIsMutable();
        namespaces_.add(index, value);
        onChanged();
      } else {
        namespacesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder addNamespaces(
        io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.add(builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder addNamespaces(
        int index, io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder builderForValue) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.add(index, builderForValue.build());
        onChanged();
      } else {
        namespacesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder addAllNamespaces(
        java.lang.Iterable<? extends io.github.chirino.memory.grpc.v1.MemoryNamespace> values) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, namespaces_);
        onChanged();
      } else {
        namespacesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder clearNamespaces() {
      if (namespacesBuilder_ == null) {
        namespaces_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        namespacesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public Builder removeNamespaces(int index) {
      if (namespacesBuilder_ == null) {
        ensureNamespacesIsMutable();
        namespaces_.remove(index);
        onChanged();
      } else {
        namespacesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder getNamespacesBuilder(
        int index) {
      return getNamespacesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder getNamespacesOrBuilder(
        int index) {
      if (namespacesBuilder_ == null) {
        return namespaces_.get(index);  } else {
        return namespacesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public java.util.List<? extends io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder> 
         getNamespacesOrBuilderList() {
      if (namespacesBuilder_ != null) {
        return namespacesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(namespaces_);
      }
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder addNamespacesBuilder() {
      return getNamespacesFieldBuilder().addBuilder(
          io.github.chirino.memory.grpc.v1.MemoryNamespace.getDefaultInstance());
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder addNamespacesBuilder(
        int index) {
      return getNamespacesFieldBuilder().addBuilder(
          index, io.github.chirino.memory.grpc.v1.MemoryNamespace.getDefaultInstance());
    }
    /**
     * <code>repeated .memory.v1.MemoryNamespace namespaces = 1;</code>
     */
    public java.util.List<io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder> 
         getNamespacesBuilderList() {
      return getNamespacesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        io.github.chirino.memory.grpc.v1.MemoryNamespace, io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder, io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder> 
        getNamespacesFieldBuilder() {
      if (namespacesBuilder_ == null) {
        namespacesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            io.github.chirino.memory.grpc.v1.MemoryNamespace, io.github.chirino.memory.grpc.v1.MemoryNamespace.Builder, io.github.chirino.memory.grpc.v1.MemoryNamespaceOrBuilder>(
                namespaces_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        namespaces_ = null;
      }
      return namespacesBuilder_;
    }

    private java.lang.Object afterCursor_ = "";
    /**
     * <code>optional string after_cursor = 2;</code>
     * @return Whether the afterCursor field is set.
     */
    public boolean hasAfterCursor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string after_cursor = 2;</code>
     * @return The afterCursor.
     */
    public java.lang.String getAfterCursor() {
      java.lang.Object ref = afterCursor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        afterCursor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string after_cursor = 2;</code>
     * @return The bytes for afterCursor.
     */
    public com.google.protobuf.ByteString
        getAfterCursorBytes() {
      java.lang.Object ref = afterCursor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        afterCursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string after_cursor = 2;</code>
     * @param value The afterCursor to set.
     * @return This builder for chaining.
     */
    public Builder setAfterCursor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      afterCursor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string after_cursor = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAfterCursor() {
      afterCursor_ = getDefaultInstance().getAfterCursor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string after_cursor = 2;</code>
     * @param value The bytes for afterCursor to set.
     * @return This builder for chaining.
     */
    public Builder setAfterCursorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      afterCursor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.AdminListMemoryNamespacesResponse)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.AdminListMemoryNamespacesResponse)
  private static final io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse();
  }

  public static io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminListMemoryNamespacesResponse>
      PARSER = new com.google.protobuf.AbstractParser<AdminListMemoryNamespacesResponse>() {
    @java.lang.Override
    public AdminListMemoryNamespacesResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminListMemoryNamespacesResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminListMemoryNamespacesResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.AdminListMemoryNamespacesResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

