// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminListMemoryNamespacesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminListMemoryNamespacesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return A list containing the namespacePrefix.
   */
  java.util.List<java.lang.String>
      getNamespacePrefixList();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return The count of namespacePrefix.
   */
  int getNamespacePrefixCount();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the element to return.
   * @return The namespacePrefix at the given index.
   */
  java.lang.String getNamespacePrefix(int index);
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the namespacePrefix at the given index.
   */
  com.google.protobuf.ByteString
      getNamespacePrefixBytes(int index);

  /**
   * <code>repeated string suffix = 2;</code>
   * @return A list containing the suffix.
   */
  java.util.List<java.lang.String>
      getSuffixList();
  /**
   * <code>repeated string suffix = 2;</code>
   * @return The count of suffix.
   */
  int getSuffixCount();
  /**
   * <code>repeated string suffix = 2;</code>
   * @param index The index of the element to return.
   * @return The suffix at the given index.
   */
  java.lang.String getSuffix(int index);
  /**
   * <code>repeated string suffix = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the suffix at the given index.
   */
  com.google.protobuf.ByteString
      getSuffixBytes(int index);

  /**
   * <code>int32 max_depth = 3;</code>
   * @return The maxDepth.
   */
  int getMaxDepth();

  /**
   * <code>.memory.v1.ArchiveFilter archived = 4;</code>
   * @return The enum numeric value on the wire for archived.
   */
  int getArchivedValue();
  /**
   * <code>.memory.v1.ArchiveFilter archived = 4;</code>
   * @return The archived.
   */
  io.github.chirino.memory.grpc.v1.ArchiveFilter getArchived();

  /**
   * <code>int32 limit = 5;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>optional string after_cursor = 6;</code>
   * @return Whether the afterCursor field is set.
   */
  boolean hasAfterCursor();
  /**
   * <code>optional string after_cursor = 6;</code>
   * @return The afterCursor.
   */
  java.lang.String getAfterCursor();
  /**
   * <code>optional string after_cursor = 6;</code>
   * @return The bytes for afterCursor.
   */
  com.google.protobuf.ByteString
      getAfterCursorBytes();

  /**
   * <code>optional string justification = 7;</code>
   * @return Whether the justification field is set.
   */
  boolean hasJustification();
  /**
   * <code>optional string justification = 7;</code>
   * @return The justification.
   */
  java.lang.String getJustification();
  /**
   * <code>optional string justification = 7;</code>
   * @return The bytes for justification.
   */
  com.google.protobuf.ByteString
      getJustificationBytes();
}
