// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.AdminConversation}
 */
public final class AdminConversation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.AdminConversation)
    AdminConversationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdminConversation.newBuilder() to construct.
  private AdminConversation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdminConversation() {
    id_ = "";
    title_ = "";
    ownerUserId_ = "";
    createdAt_ = "";
    updatedAt_ = "";
    lastMessagePreview_ = "";
    accessLevel_ = 0;
    startedByConversationId_ = "";
    startedByEntryId_ = com.google.protobuf.ByteString.EMPTY;
    clientId_ = "";
    agentId_ = "";
    forkedAtEntryId_ = com.google.protobuf.ByteString.EMPTY;
    forkedAtConversationId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new AdminConversation();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminConversation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminConversation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.AdminConversation.class, io.github.chirino.memory.grpc.v1.AdminConversation.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OWNER_USER_ID_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object ownerUserId_ = "";
  /**
   * <code>string owner_user_id = 3;</code>
   * @return The ownerUserId.
   */
  @java.lang.Override
  public java.lang.String getOwnerUserId() {
    java.lang.Object ref = ownerUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ownerUserId_ = s;
      return s;
    }
  }
  /**
   * <code>string owner_user_id = 3;</code>
   * @return The bytes for ownerUserId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOwnerUserIdBytes() {
    java.lang.Object ref = ownerUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ownerUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object createdAt_ = "";
  /**
   * <code>string created_at = 4;</code>
   * @return The createdAt.
   */
  @java.lang.Override
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <code>string created_at = 4;</code>
   * @return The bytes for createdAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATED_AT_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object updatedAt_ = "";
  /**
   * <code>string updated_at = 5;</code>
   * @return The updatedAt.
   */
  @java.lang.Override
  public java.lang.String getUpdatedAt() {
    java.lang.Object ref = updatedAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedAt_ = s;
      return s;
    }
  }
  /**
   * <code>string updated_at = 5;</code>
   * @return The bytes for updatedAt.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUpdatedAtBytes() {
    java.lang.Object ref = updatedAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MESSAGE_PREVIEW_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastMessagePreview_ = "";
  /**
   * <code>string last_message_preview = 6;</code>
   * @return The lastMessagePreview.
   */
  @java.lang.Override
  public java.lang.String getLastMessagePreview() {
    java.lang.Object ref = lastMessagePreview_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastMessagePreview_ = s;
      return s;
    }
  }
  /**
   * <code>string last_message_preview = 6;</code>
   * @return The bytes for lastMessagePreview.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastMessagePreviewBytes() {
    java.lang.Object ref = lastMessagePreview_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastMessagePreview_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESS_LEVEL_FIELD_NUMBER = 7;
  private int accessLevel_ = 0;
  /**
   * <code>.memory.v1.AccessLevel access_level = 7;</code>
   * @return The enum numeric value on the wire for accessLevel.
   */
  @java.lang.Override public int getAccessLevelValue() {
    return accessLevel_;
  }
  /**
   * <code>.memory.v1.AccessLevel access_level = 7;</code>
   * @return The accessLevel.
   */
  @java.lang.Override public io.github.chirino.memory.grpc.v1.AccessLevel getAccessLevel() {
    io.github.chirino.memory.grpc.v1.AccessLevel result = io.github.chirino.memory.grpc.v1.AccessLevel.forNumber(accessLevel_);
    return result == null ? io.github.chirino.memory.grpc.v1.AccessLevel.UNRECOGNIZED : result;
  }

  public static final int STARTED_BY_CONVERSATION_ID_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private volatile java.lang.Object startedByConversationId_ = "";
  /**
   * <code>string started_by_conversation_id = 8;</code>
   * @return The startedByConversationId.
   */
  @java.lang.Override
  public java.lang.String getStartedByConversationId() {
    java.lang.Object ref = startedByConversationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      startedByConversationId_ = s;
      return s;
    }
  }
  /**
   * <code>string started_by_conversation_id = 8;</code>
   * @return The bytes for startedByConversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStartedByConversationIdBytes() {
    java.lang.Object ref = startedByConversationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      startedByConversationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STARTED_BY_ENTRY_ID_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString startedByEntryId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes started_by_entry_id = 9;</code>
   * @return The startedByEntryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getStartedByEntryId() {
    return startedByEntryId_;
  }

  public static final int ARCHIVED_FIELD_NUMBER = 10;
  private boolean archived_ = false;
  /**
   * <code>bool archived = 10;</code>
   * @return The archived.
   */
  @java.lang.Override
  public boolean getArchived() {
    return archived_;
  }

  public static final int CLIENT_ID_FIELD_NUMBER = 11;
  @SuppressWarnings("serial")
  private volatile java.lang.Object clientId_ = "";
  /**
   * <code>string client_id = 11;</code>
   * @return The clientId.
   */
  @java.lang.Override
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <code>string client_id = 11;</code>
   * @return The bytes for clientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGENT_ID_FIELD_NUMBER = 12;
  @SuppressWarnings("serial")
  private volatile java.lang.Object agentId_ = "";
  /**
   * <code>optional string agent_id = 12;</code>
   * @return Whether the agentId field is set.
   */
  @java.lang.Override
  public boolean hasAgentId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional string agent_id = 12;</code>
   * @return The agentId.
   */
  @java.lang.Override
  public java.lang.String getAgentId() {
    java.lang.Object ref = agentId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      agentId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string agent_id = 12;</code>
   * @return The bytes for agentId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgentIdBytes() {
    java.lang.Object ref = agentId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      agentId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METADATA_FIELD_NUMBER = 13;
  private com.google.protobuf.Struct metadata_;
  /**
   * <code>.google.protobuf.Struct metadata = 13;</code>
   * @return Whether the metadata field is set.
   */
  @java.lang.Override
  public boolean hasMetadata() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.google.protobuf.Struct metadata = 13;</code>
   * @return The metadata.
   */
  @java.lang.Override
  public com.google.protobuf.Struct getMetadata() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }
  /**
   * <code>.google.protobuf.Struct metadata = 13;</code>
   */
  @java.lang.Override
  public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
    return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
  }

  public static final int FORKED_AT_ENTRY_ID_FIELD_NUMBER = 14;
  private com.google.protobuf.ByteString forkedAtEntryId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes forked_at_entry_id = 14;</code>
   * @return The forkedAtEntryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getForkedAtEntryId() {
    return forkedAtEntryId_;
  }

  public static final int FORKED_AT_CONVERSATION_ID_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object forkedAtConversationId_ = "";
  /**
   * <code>string forked_at_conversation_id = 15;</code>
   * @return The forkedAtConversationId.
   */
  @java.lang.Override
  public java.lang.String getForkedAtConversationId() {
    java.lang.Object ref = forkedAtConversationId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      forkedAtConversationId_ = s;
      return s;
    }
  }
  /**
   * <code>string forked_at_conversation_id = 15;</code>
   * @return The bytes for forkedAtConversationId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getForkedAtConversationIdBytes() {
    java.lang.Object ref = forkedAtConversationId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      forkedAtConversationId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HAS_RESPONSE_IN_PROGRESS_FIELD_NUMBER = 16;
  private boolean hasResponseInProgress_ = false;
  /**
   * <code>bool has_response_in_progress = 16;</code>
   * @return The hasResponseInProgress.
   */
  @java.lang.Override
  public boolean getHasResponseInProgress() {
    return hasResponseInProgress_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerUserId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ownerUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdAt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, createdAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updatedAt_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, updatedAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastMessagePreview_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, lastMessagePreview_);
    }
    if (accessLevel_ != io.github.chirino.memory.grpc.v1.AccessLevel.ACCESS_LEVEL_UNSPECIFIED.getNumber()) {
      output.writeEnum(7, accessLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startedByConversationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, startedByConversationId_);
    }
    if (!startedByEntryId_.isEmpty()) {
      output.writeBytes(9, startedByEntryId_);
    }
    if (archived_ != false) {
      output.writeBool(10, archived_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, clientId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, agentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(13, getMetadata());
    }
    if (!forkedAtEntryId_.isEmpty()) {
      output.writeBytes(14, forkedAtEntryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forkedAtConversationId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, forkedAtConversationId_);
    }
    if (hasResponseInProgress_ != false) {
      output.writeBool(16, hasResponseInProgress_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ownerUserId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ownerUserId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(createdAt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, createdAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(updatedAt_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, updatedAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastMessagePreview_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, lastMessagePreview_);
    }
    if (accessLevel_ != io.github.chirino.memory.grpc.v1.AccessLevel.ACCESS_LEVEL_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, accessLevel_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(startedByConversationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, startedByConversationId_);
    }
    if (!startedByEntryId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, startedByEntryId_);
    }
    if (archived_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(10, archived_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(clientId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, clientId_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, agentId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(13, getMetadata());
    }
    if (!forkedAtEntryId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(14, forkedAtEntryId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(forkedAtConversationId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, forkedAtConversationId_);
    }
    if (hasResponseInProgress_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(16, hasResponseInProgress_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.AdminConversation)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.AdminConversation other = (io.github.chirino.memory.grpc.v1.AdminConversation) obj;

    if (!getId()
        .equals(other.getId())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getOwnerUserId()
        .equals(other.getOwnerUserId())) return false;
    if (!getCreatedAt()
        .equals(other.getCreatedAt())) return false;
    if (!getUpdatedAt()
        .equals(other.getUpdatedAt())) return false;
    if (!getLastMessagePreview()
        .equals(other.getLastMessagePreview())) return false;
    if (accessLevel_ != other.accessLevel_) return false;
    if (!getStartedByConversationId()
        .equals(other.getStartedByConversationId())) return false;
    if (!getStartedByEntryId()
        .equals(other.getStartedByEntryId())) return false;
    if (getArchived()
        != other.getArchived()) return false;
    if (!getClientId()
        .equals(other.getClientId())) return false;
    if (hasAgentId() != other.hasAgentId()) return false;
    if (hasAgentId()) {
      if (!getAgentId()
          .equals(other.getAgentId())) return false;
    }
    if (hasMetadata() != other.hasMetadata()) return false;
    if (hasMetadata()) {
      if (!getMetadata()
          .equals(other.getMetadata())) return false;
    }
    if (!getForkedAtEntryId()
        .equals(other.getForkedAtEntryId())) return false;
    if (!getForkedAtConversationId()
        .equals(other.getForkedAtConversationId())) return false;
    if (getHasResponseInProgress()
        != other.getHasResponseInProgress()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + OWNER_USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getOwnerUserId().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedAt().hashCode();
    hash = (37 * hash) + LAST_MESSAGE_PREVIEW_FIELD_NUMBER;
    hash = (53 * hash) + getLastMessagePreview().hashCode();
    hash = (37 * hash) + ACCESS_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + accessLevel_;
    hash = (37 * hash) + STARTED_BY_CONVERSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStartedByConversationId().hashCode();
    hash = (37 * hash) + STARTED_BY_ENTRY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getStartedByEntryId().hashCode();
    hash = (37 * hash) + ARCHIVED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getArchived());
    hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    if (hasAgentId()) {
      hash = (37 * hash) + AGENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getAgentId().hashCode();
    }
    if (hasMetadata()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetadata().hashCode();
    }
    hash = (37 * hash) + FORKED_AT_ENTRY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getForkedAtEntryId().hashCode();
    hash = (37 * hash) + FORKED_AT_CONVERSATION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getForkedAtConversationId().hashCode();
    hash = (37 * hash) + HAS_RESPONSE_IN_PROGRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHasResponseInProgress());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.AdminConversation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.AdminConversation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.AdminConversation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.AdminConversation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.AdminConversation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.AdminConversation)
      io.github.chirino.memory.grpc.v1.AdminConversationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminConversation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminConversation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.AdminConversation.class, io.github.chirino.memory.grpc.v1.AdminConversation.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.AdminConversation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      title_ = "";
      ownerUserId_ = "";
      createdAt_ = "";
      updatedAt_ = "";
      lastMessagePreview_ = "";
      accessLevel_ = 0;
      startedByConversationId_ = "";
      startedByEntryId_ = com.google.protobuf.ByteString.EMPTY;
      archived_ = false;
      clientId_ = "";
      agentId_ = "";
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      forkedAtEntryId_ = com.google.protobuf.ByteString.EMPTY;
      forkedAtConversationId_ = "";
      hasResponseInProgress_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_AdminConversation_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminConversation getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.AdminConversation.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminConversation build() {
      io.github.chirino.memory.grpc.v1.AdminConversation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AdminConversation buildPartial() {
      io.github.chirino.memory.grpc.v1.AdminConversation result = new io.github.chirino.memory.grpc.v1.AdminConversation(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.AdminConversation result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.ownerUserId_ = ownerUserId_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.createdAt_ = createdAt_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.updatedAt_ = updatedAt_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.lastMessagePreview_ = lastMessagePreview_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.accessLevel_ = accessLevel_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.startedByConversationId_ = startedByConversationId_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.startedByEntryId_ = startedByEntryId_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.archived_ = archived_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.clientId_ = clientId_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.agentId_ = agentId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.metadata_ = metadataBuilder_ == null
            ? metadata_
            : metadataBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.forkedAtEntryId_ = forkedAtEntryId_;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.forkedAtConversationId_ = forkedAtConversationId_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.hasResponseInProgress_ = hasResponseInProgress_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.AdminConversation) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.AdminConversation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.AdminConversation other) {
      if (other == io.github.chirino.memory.grpc.v1.AdminConversation.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getOwnerUserId().isEmpty()) {
        ownerUserId_ = other.ownerUserId_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getUpdatedAt().isEmpty()) {
        updatedAt_ = other.updatedAt_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getLastMessagePreview().isEmpty()) {
        lastMessagePreview_ = other.lastMessagePreview_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (other.accessLevel_ != 0) {
        setAccessLevelValue(other.getAccessLevelValue());
      }
      if (!other.getStartedByConversationId().isEmpty()) {
        startedByConversationId_ = other.startedByConversationId_;
        bitField0_ |= 0x00000080;
        onChanged();
      }
      if (other.getStartedByEntryId() != com.google.protobuf.ByteString.EMPTY) {
        setStartedByEntryId(other.getStartedByEntryId());
      }
      if (other.getArchived() != false) {
        setArchived(other.getArchived());
      }
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        bitField0_ |= 0x00000400;
        onChanged();
      }
      if (other.hasAgentId()) {
        agentId_ = other.agentId_;
        bitField0_ |= 0x00000800;
        onChanged();
      }
      if (other.hasMetadata()) {
        mergeMetadata(other.getMetadata());
      }
      if (other.getForkedAtEntryId() != com.google.protobuf.ByteString.EMPTY) {
        setForkedAtEntryId(other.getForkedAtEntryId());
      }
      if (!other.getForkedAtConversationId().isEmpty()) {
        forkedAtConversationId_ = other.forkedAtConversationId_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (other.getHasResponseInProgress() != false) {
        setHasResponseInProgress(other.getHasResponseInProgress());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              ownerUserId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              createdAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              updatedAt_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              lastMessagePreview_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 56: {
              accessLevel_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 66: {
              startedByConversationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              startedByEntryId_ = input.readBytes();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              archived_ = input.readBool();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 90: {
              clientId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000400;
              break;
            } // case 90
            case 98: {
              agentId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000800;
              break;
            } // case 98
            case 106: {
              input.readMessage(
                  getMetadataFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00001000;
              break;
            } // case 106
            case 114: {
              forkedAtEntryId_ = input.readBytes();
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              forkedAtConversationId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 128: {
              hasResponseInProgress_ = input.readBool();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object ownerUserId_ = "";
    /**
     * <code>string owner_user_id = 3;</code>
     * @return The ownerUserId.
     */
    public java.lang.String getOwnerUserId() {
      java.lang.Object ref = ownerUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ownerUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string owner_user_id = 3;</code>
     * @return The bytes for ownerUserId.
     */
    public com.google.protobuf.ByteString
        getOwnerUserIdBytes() {
      java.lang.Object ref = ownerUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string owner_user_id = 3;</code>
     * @param value The ownerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ownerUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string owner_user_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOwnerUserId() {
      ownerUserId_ = getDefaultInstance().getOwnerUserId();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string owner_user_id = 3;</code>
     * @param value The bytes for ownerUserId to set.
     * @return This builder for chaining.
     */
    public Builder setOwnerUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ownerUserId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <code>string created_at = 4;</code>
     * @return The createdAt.
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string created_at = 4;</code>
     * @return The bytes for createdAt.
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string created_at = 4;</code>
     * @param value The createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      createdAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreatedAt() {
      createdAt_ = getDefaultInstance().getCreatedAt();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string created_at = 4;</code>
     * @param value The bytes for createdAt to set.
     * @return This builder for chaining.
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      createdAt_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object updatedAt_ = "";
    /**
     * <code>string updated_at = 5;</code>
     * @return The updatedAt.
     */
    public java.lang.String getUpdatedAt() {
      java.lang.Object ref = updatedAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string updated_at = 5;</code>
     * @return The bytes for updatedAt.
     */
    public com.google.protobuf.ByteString
        getUpdatedAtBytes() {
      java.lang.Object ref = updatedAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string updated_at = 5;</code>
     * @param value The updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAt(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      updatedAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string updated_at = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearUpdatedAt() {
      updatedAt_ = getDefaultInstance().getUpdatedAt();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string updated_at = 5;</code>
     * @param value The bytes for updatedAt to set.
     * @return This builder for chaining.
     */
    public Builder setUpdatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      updatedAt_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object lastMessagePreview_ = "";
    /**
     * <code>string last_message_preview = 6;</code>
     * @return The lastMessagePreview.
     */
    public java.lang.String getLastMessagePreview() {
      java.lang.Object ref = lastMessagePreview_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastMessagePreview_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_message_preview = 6;</code>
     * @return The bytes for lastMessagePreview.
     */
    public com.google.protobuf.ByteString
        getLastMessagePreviewBytes() {
      java.lang.Object ref = lastMessagePreview_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastMessagePreview_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_message_preview = 6;</code>
     * @param value The lastMessagePreview to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessagePreview(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastMessagePreview_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string last_message_preview = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastMessagePreview() {
      lastMessagePreview_ = getDefaultInstance().getLastMessagePreview();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string last_message_preview = 6;</code>
     * @param value The bytes for lastMessagePreview to set.
     * @return This builder for chaining.
     */
    public Builder setLastMessagePreviewBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastMessagePreview_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private int accessLevel_ = 0;
    /**
     * <code>.memory.v1.AccessLevel access_level = 7;</code>
     * @return The enum numeric value on the wire for accessLevel.
     */
    @java.lang.Override public int getAccessLevelValue() {
      return accessLevel_;
    }
    /**
     * <code>.memory.v1.AccessLevel access_level = 7;</code>
     * @param value The enum numeric value on the wire for accessLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAccessLevelValue(int value) {
      accessLevel_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.memory.v1.AccessLevel access_level = 7;</code>
     * @return The accessLevel.
     */
    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.AccessLevel getAccessLevel() {
      io.github.chirino.memory.grpc.v1.AccessLevel result = io.github.chirino.memory.grpc.v1.AccessLevel.forNumber(accessLevel_);
      return result == null ? io.github.chirino.memory.grpc.v1.AccessLevel.UNRECOGNIZED : result;
    }
    /**
     * <code>.memory.v1.AccessLevel access_level = 7;</code>
     * @param value The accessLevel to set.
     * @return This builder for chaining.
     */
    public Builder setAccessLevel(io.github.chirino.memory.grpc.v1.AccessLevel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      accessLevel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.memory.v1.AccessLevel access_level = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessLevel() {
      bitField0_ = (bitField0_ & ~0x00000040);
      accessLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object startedByConversationId_ = "";
    /**
     * <code>string started_by_conversation_id = 8;</code>
     * @return The startedByConversationId.
     */
    public java.lang.String getStartedByConversationId() {
      java.lang.Object ref = startedByConversationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        startedByConversationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string started_by_conversation_id = 8;</code>
     * @return The bytes for startedByConversationId.
     */
    public com.google.protobuf.ByteString
        getStartedByConversationIdBytes() {
      java.lang.Object ref = startedByConversationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        startedByConversationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string started_by_conversation_id = 8;</code>
     * @param value The startedByConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setStartedByConversationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      startedByConversationId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>string started_by_conversation_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedByConversationId() {
      startedByConversationId_ = getDefaultInstance().getStartedByConversationId();
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <code>string started_by_conversation_id = 8;</code>
     * @param value The bytes for startedByConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setStartedByConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      startedByConversationId_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString startedByEntryId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes started_by_entry_id = 9;</code>
     * @return The startedByEntryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getStartedByEntryId() {
      return startedByEntryId_;
    }
    /**
     * <code>bytes started_by_entry_id = 9;</code>
     * @param value The startedByEntryId to set.
     * @return This builder for chaining.
     */
    public Builder setStartedByEntryId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      startedByEntryId_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>bytes started_by_entry_id = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartedByEntryId() {
      bitField0_ = (bitField0_ & ~0x00000100);
      startedByEntryId_ = getDefaultInstance().getStartedByEntryId();
      onChanged();
      return this;
    }

    private boolean archived_ ;
    /**
     * <code>bool archived = 10;</code>
     * @return The archived.
     */
    @java.lang.Override
    public boolean getArchived() {
      return archived_;
    }
    /**
     * <code>bool archived = 10;</code>
     * @param value The archived to set.
     * @return This builder for chaining.
     */
    public Builder setArchived(boolean value) {

      archived_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>bool archived = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearArchived() {
      bitField0_ = (bitField0_ & ~0x00000200);
      archived_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object clientId_ = "";
    /**
     * <code>string client_id = 11;</code>
     * @return The clientId.
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string client_id = 11;</code>
     * @return The bytes for clientId.
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string client_id = 11;</code>
     * @param value The clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      clientId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientId() {
      clientId_ = getDefaultInstance().getClientId();
      bitField0_ = (bitField0_ & ~0x00000400);
      onChanged();
      return this;
    }
    /**
     * <code>string client_id = 11;</code>
     * @param value The bytes for clientId to set.
     * @return This builder for chaining.
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      clientId_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }

    private java.lang.Object agentId_ = "";
    /**
     * <code>optional string agent_id = 12;</code>
     * @return Whether the agentId field is set.
     */
    public boolean hasAgentId() {
      return ((bitField0_ & 0x00000800) != 0);
    }
    /**
     * <code>optional string agent_id = 12;</code>
     * @return The agentId.
     */
    public java.lang.String getAgentId() {
      java.lang.Object ref = agentId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        agentId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string agent_id = 12;</code>
     * @return The bytes for agentId.
     */
    public com.google.protobuf.ByteString
        getAgentIdBytes() {
      java.lang.Object ref = agentId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        agentId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string agent_id = 12;</code>
     * @param value The agentId to set.
     * @return This builder for chaining.
     */
    public Builder setAgentId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      agentId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>optional string agent_id = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgentId() {
      agentId_ = getDefaultInstance().getAgentId();
      bitField0_ = (bitField0_ & ~0x00000800);
      onChanged();
      return this;
    }
    /**
     * <code>optional string agent_id = 12;</code>
     * @param value The bytes for agentId to set.
     * @return This builder for chaining.
     */
    public Builder setAgentIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      agentId_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }

    private com.google.protobuf.Struct metadata_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> metadataBuilder_;
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     * @return Whether the metadata field is set.
     */
    public boolean hasMetadata() {
      return ((bitField0_ & 0x00001000) != 0);
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     * @return The metadata.
     */
    public com.google.protobuf.Struct getMetadata() {
      if (metadataBuilder_ == null) {
        return metadata_ == null ? com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      } else {
        return metadataBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public Builder setMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        metadata_ = value;
      } else {
        metadataBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public Builder setMetadata(
        com.google.protobuf.Struct.Builder builderForValue) {
      if (metadataBuilder_ == null) {
        metadata_ = builderForValue.build();
      } else {
        metadataBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public Builder mergeMetadata(com.google.protobuf.Struct value) {
      if (metadataBuilder_ == null) {
        if (((bitField0_ & 0x00001000) != 0) &&
          metadata_ != null &&
          metadata_ != com.google.protobuf.Struct.getDefaultInstance()) {
          getMetadataBuilder().mergeFrom(value);
        } else {
          metadata_ = value;
        }
      } else {
        metadataBuilder_.mergeFrom(value);
      }
      if (metadata_ != null) {
        bitField0_ |= 0x00001000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00001000);
      metadata_ = null;
      if (metadataBuilder_ != null) {
        metadataBuilder_.dispose();
        metadataBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public com.google.protobuf.Struct.Builder getMetadataBuilder() {
      bitField0_ |= 0x00001000;
      onChanged();
      return getMetadataFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    public com.google.protobuf.StructOrBuilder getMetadataOrBuilder() {
      if (metadataBuilder_ != null) {
        return metadataBuilder_.getMessageOrBuilder();
      } else {
        return metadata_ == null ?
            com.google.protobuf.Struct.getDefaultInstance() : metadata_;
      }
    }
    /**
     * <code>.google.protobuf.Struct metadata = 13;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder> 
        getMetadataFieldBuilder() {
      if (metadataBuilder_ == null) {
        metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Struct, com.google.protobuf.Struct.Builder, com.google.protobuf.StructOrBuilder>(
                getMetadata(),
                getParentForChildren(),
                isClean());
        metadata_ = null;
      }
      return metadataBuilder_;
    }

    private com.google.protobuf.ByteString forkedAtEntryId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes forked_at_entry_id = 14;</code>
     * @return The forkedAtEntryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getForkedAtEntryId() {
      return forkedAtEntryId_;
    }
    /**
     * <code>bytes forked_at_entry_id = 14;</code>
     * @param value The forkedAtEntryId to set.
     * @return This builder for chaining.
     */
    public Builder setForkedAtEntryId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      forkedAtEntryId_ = value;
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>bytes forked_at_entry_id = 14;</code>
     * @return This builder for chaining.
     */
    public Builder clearForkedAtEntryId() {
      bitField0_ = (bitField0_ & ~0x00002000);
      forkedAtEntryId_ = getDefaultInstance().getForkedAtEntryId();
      onChanged();
      return this;
    }

    private java.lang.Object forkedAtConversationId_ = "";
    /**
     * <code>string forked_at_conversation_id = 15;</code>
     * @return The forkedAtConversationId.
     */
    public java.lang.String getForkedAtConversationId() {
      java.lang.Object ref = forkedAtConversationId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        forkedAtConversationId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string forked_at_conversation_id = 15;</code>
     * @return The bytes for forkedAtConversationId.
     */
    public com.google.protobuf.ByteString
        getForkedAtConversationIdBytes() {
      java.lang.Object ref = forkedAtConversationId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        forkedAtConversationId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string forked_at_conversation_id = 15;</code>
     * @param value The forkedAtConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setForkedAtConversationId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      forkedAtConversationId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <code>string forked_at_conversation_id = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearForkedAtConversationId() {
      forkedAtConversationId_ = getDefaultInstance().getForkedAtConversationId();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <code>string forked_at_conversation_id = 15;</code>
     * @param value The bytes for forkedAtConversationId to set.
     * @return This builder for chaining.
     */
    public Builder setForkedAtConversationIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      forkedAtConversationId_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private boolean hasResponseInProgress_ ;
    /**
     * <code>bool has_response_in_progress = 16;</code>
     * @return The hasResponseInProgress.
     */
    @java.lang.Override
    public boolean getHasResponseInProgress() {
      return hasResponseInProgress_;
    }
    /**
     * <code>bool has_response_in_progress = 16;</code>
     * @param value The hasResponseInProgress to set.
     * @return This builder for chaining.
     */
    public Builder setHasResponseInProgress(boolean value) {

      hasResponseInProgress_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <code>bool has_response_in_progress = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearHasResponseInProgress() {
      bitField0_ = (bitField0_ & ~0x00008000);
      hasResponseInProgress_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.AdminConversation)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.AdminConversation)
  private static final io.github.chirino.memory.grpc.v1.AdminConversation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.AdminConversation();
  }

  public static io.github.chirino.memory.grpc.v1.AdminConversation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdminConversation>
      PARSER = new com.google.protobuf.AbstractParser<AdminConversation>() {
    @java.lang.Override
    public AdminConversation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AdminConversation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdminConversation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.AdminConversation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

