// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminSearchMemoriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminSearchMemoriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return A list containing the namespacePrefix.
   */
  java.util.List<java.lang.String>
      getNamespacePrefixList();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return The count of namespacePrefix.
   */
  int getNamespacePrefixCount();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the element to return.
   * @return The namespacePrefix at the given index.
   */
  java.lang.String getNamespacePrefix(int index);
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the namespacePrefix at the given index.
   */
  com.google.protobuf.ByteString
      getNamespacePrefixBytes(int index);

  /**
   * <code>optional string key_prefix = 2;</code>
   * @return Whether the keyPrefix field is set.
   */
  boolean hasKeyPrefix();
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The keyPrefix.
   */
  java.lang.String getKeyPrefix();
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The bytes for keyPrefix.
   */
  com.google.protobuf.ByteString
      getKeyPrefixBytes();

  /**
   * <code>string query = 3;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 3;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   * @return Whether the filter field is set.
   */
  boolean hasFilter();
  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   * @return The filter.
   */
  com.google.protobuf.Struct getFilter();
  /**
   * <code>optional .google.protobuf.Struct filter = 4;</code>
   */
  com.google.protobuf.StructOrBuilder getFilterOrBuilder();

  /**
   * <code>.memory.v1.ArchiveFilter archived = 5;</code>
   * @return The enum numeric value on the wire for archived.
   */
  int getArchivedValue();
  /**
   * <code>.memory.v1.ArchiveFilter archived = 5;</code>
   * @return The archived.
   */
  io.github.chirino.memory.grpc.v1.ArchiveFilter getArchived();

  /**
   * <code>bool include_usage = 6;</code>
   * @return The includeUsage.
   */
  boolean getIncludeUsage();

  /**
   * <code>int32 limit = 7;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>optional string justification = 8;</code>
   * @return Whether the justification field is set.
   */
  boolean hasJustification();
  /**
   * <code>optional string justification = 8;</code>
   * @return The justification.
   */
  java.lang.String getJustification();
  /**
   * <code>optional string justification = 8;</code>
   * @return The bytes for justification.
   */
  com.google.protobuf.ByteString
      getJustificationBytes();

  /**
   * <code>optional string as_user_id = 9;</code>
   * @return Whether the asUserId field is set.
   */
  boolean hasAsUserId();
  /**
   * <code>optional string as_user_id = 9;</code>
   * @return The asUserId.
   */
  java.lang.String getAsUserId();
  /**
   * <code>optional string as_user_id = 9;</code>
   * @return The bytes for asUserId.
   */
  com.google.protobuf.ByteString
      getAsUserIdBytes();

  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  java.util.List<io.github.chirino.memory.grpc.v1.MemorySearchQuery> 
      getQueriesList();
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  io.github.chirino.memory.grpc.v1.MemorySearchQuery getQueries(int index);
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  int getQueriesCount();
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  java.util.List<? extends io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder> 
      getQueriesOrBuilderList();
  /**
   * <code>repeated .memory.v1.MemorySearchQuery queries = 10;</code>
   */
  io.github.chirino.memory.grpc.v1.MemorySearchQueryOrBuilder getQueriesOrBuilder(
      int index);

  /**
   * <code>int32 per_query_limit = 11;</code>
   * @return The perQueryLimit.
   */
  int getPerQueryLimit();
}
