// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface AdminListMemoriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.AdminListMemoriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return A list containing the namespacePrefix.
   */
  java.util.List<java.lang.String>
      getNamespacePrefixList();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @return The count of namespacePrefix.
   */
  int getNamespacePrefixCount();
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the element to return.
   * @return The namespacePrefix at the given index.
   */
  java.lang.String getNamespacePrefix(int index);
  /**
   * <code>repeated string namespace_prefix = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the namespacePrefix at the given index.
   */
  com.google.protobuf.ByteString
      getNamespacePrefixBytes(int index);

  /**
   * <code>optional string key_prefix = 2;</code>
   * @return Whether the keyPrefix field is set.
   */
  boolean hasKeyPrefix();
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The keyPrefix.
   */
  java.lang.String getKeyPrefix();
  /**
   * <code>optional string key_prefix = 2;</code>
   * @return The bytes for keyPrefix.
   */
  com.google.protobuf.ByteString
      getKeyPrefixBytes();

  /**
   * <code>.memory.v1.ArchiveFilter archived = 3;</code>
   * @return The enum numeric value on the wire for archived.
   */
  int getArchivedValue();
  /**
   * <code>.memory.v1.ArchiveFilter archived = 3;</code>
   * @return The archived.
   */
  io.github.chirino.memory.grpc.v1.ArchiveFilter getArchived();

  /**
   * <code>optional .google.protobuf.Timestamp created_after = 4;</code>
   * @return Whether the createdAfter field is set.
   */
  boolean hasCreatedAfter();
  /**
   * <code>optional .google.protobuf.Timestamp created_after = 4;</code>
   * @return The createdAfter.
   */
  com.google.protobuf.Timestamp getCreatedAfter();
  /**
   * <code>optional .google.protobuf.Timestamp created_after = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedAfterOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp created_before = 5;</code>
   * @return Whether the createdBefore field is set.
   */
  boolean hasCreatedBefore();
  /**
   * <code>optional .google.protobuf.Timestamp created_before = 5;</code>
   * @return The createdBefore.
   */
  com.google.protobuf.Timestamp getCreatedBefore();
  /**
   * <code>optional .google.protobuf.Timestamp created_before = 5;</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreatedBeforeOrBuilder();

  /**
   * <code>optional .google.protobuf.Timestamp expires_before = 6;</code>
   * @return Whether the expiresBefore field is set.
   */
  boolean hasExpiresBefore();
  /**
   * <code>optional .google.protobuf.Timestamp expires_before = 6;</code>
   * @return The expiresBefore.
   */
  com.google.protobuf.Timestamp getExpiresBefore();
  /**
   * <code>optional .google.protobuf.Timestamp expires_before = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiresBeforeOrBuilder();

  /**
   * <code>bool include_usage = 7;</code>
   * @return The includeUsage.
   */
  boolean getIncludeUsage();

  /**
   * <code>int32 limit = 8;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <code>optional string after_cursor = 9;</code>
   * @return Whether the afterCursor field is set.
   */
  boolean hasAfterCursor();
  /**
   * <code>optional string after_cursor = 9;</code>
   * @return The afterCursor.
   */
  java.lang.String getAfterCursor();
  /**
   * <code>optional string after_cursor = 9;</code>
   * @return The bytes for afterCursor.
   */
  com.google.protobuf.ByteString
      getAfterCursorBytes();

  /**
   * <code>optional string justification = 10;</code>
   * @return Whether the justification field is set.
   */
  boolean hasJustification();
  /**
   * <code>optional string justification = 10;</code>
   * @return The justification.
   */
  java.lang.String getJustification();
  /**
   * <code>optional string justification = 10;</code>
   * @return The bytes for justification.
   */
  com.google.protobuf.ByteString
      getJustificationBytes();
}
