// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface CapabilitiesAuthOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.CapabilitiesAuth)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool oidc_enabled = 1;</code>
   * @return The oidcEnabled.
   */
  boolean getOidcEnabled();

  /**
   * <code>bool api_key_enabled = 2;</code>
   * @return The apiKeyEnabled.
   */
  boolean getApiKeyEnabled();

  /**
   * <code>bool admin_justification_required = 3;</code>
   * @return The adminJustificationRequired.
   */
  boolean getAdminJustificationRequired();
}
