// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.CapabilitiesAuth}
 */
public final class CapabilitiesAuth extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.CapabilitiesAuth)
    CapabilitiesAuthOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CapabilitiesAuth.newBuilder() to construct.
  private CapabilitiesAuth(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CapabilitiesAuth() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CapabilitiesAuth();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesAuth_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesAuth_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.CapabilitiesAuth.class, io.github.chirino.memory.grpc.v1.CapabilitiesAuth.Builder.class);
  }

  public static final int OIDC_ENABLED_FIELD_NUMBER = 1;
  private boolean oidcEnabled_ = false;
  /**
   * <code>bool oidc_enabled = 1;</code>
   * @return The oidcEnabled.
   */
  @java.lang.Override
  public boolean getOidcEnabled() {
    return oidcEnabled_;
  }

  public static final int API_KEY_ENABLED_FIELD_NUMBER = 2;
  private boolean apiKeyEnabled_ = false;
  /**
   * <code>bool api_key_enabled = 2;</code>
   * @return The apiKeyEnabled.
   */
  @java.lang.Override
  public boolean getApiKeyEnabled() {
    return apiKeyEnabled_;
  }

  public static final int ADMIN_JUSTIFICATION_REQUIRED_FIELD_NUMBER = 3;
  private boolean adminJustificationRequired_ = false;
  /**
   * <code>bool admin_justification_required = 3;</code>
   * @return The adminJustificationRequired.
   */
  @java.lang.Override
  public boolean getAdminJustificationRequired() {
    return adminJustificationRequired_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (oidcEnabled_ != false) {
      output.writeBool(1, oidcEnabled_);
    }
    if (apiKeyEnabled_ != false) {
      output.writeBool(2, apiKeyEnabled_);
    }
    if (adminJustificationRequired_ != false) {
      output.writeBool(3, adminJustificationRequired_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (oidcEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, oidcEnabled_);
    }
    if (apiKeyEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, apiKeyEnabled_);
    }
    if (adminJustificationRequired_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, adminJustificationRequired_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.CapabilitiesAuth)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.CapabilitiesAuth other = (io.github.chirino.memory.grpc.v1.CapabilitiesAuth) obj;

    if (getOidcEnabled()
        != other.getOidcEnabled()) return false;
    if (getApiKeyEnabled()
        != other.getApiKeyEnabled()) return false;
    if (getAdminJustificationRequired()
        != other.getAdminJustificationRequired()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OIDC_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOidcEnabled());
    hash = (37 * hash) + API_KEY_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getApiKeyEnabled());
    hash = (37 * hash) + ADMIN_JUSTIFICATION_REQUIRED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAdminJustificationRequired());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.CapabilitiesAuth prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.CapabilitiesAuth}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.CapabilitiesAuth)
      io.github.chirino.memory.grpc.v1.CapabilitiesAuthOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesAuth_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesAuth_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.CapabilitiesAuth.class, io.github.chirino.memory.grpc.v1.CapabilitiesAuth.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.CapabilitiesAuth.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      oidcEnabled_ = false;
      apiKeyEnabled_ = false;
      adminJustificationRequired_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesAuth_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesAuth getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.CapabilitiesAuth.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesAuth build() {
      io.github.chirino.memory.grpc.v1.CapabilitiesAuth result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesAuth buildPartial() {
      io.github.chirino.memory.grpc.v1.CapabilitiesAuth result = new io.github.chirino.memory.grpc.v1.CapabilitiesAuth(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.CapabilitiesAuth result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.oidcEnabled_ = oidcEnabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.apiKeyEnabled_ = apiKeyEnabled_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.adminJustificationRequired_ = adminJustificationRequired_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.CapabilitiesAuth) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.CapabilitiesAuth)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.CapabilitiesAuth other) {
      if (other == io.github.chirino.memory.grpc.v1.CapabilitiesAuth.getDefaultInstance()) return this;
      if (other.getOidcEnabled() != false) {
        setOidcEnabled(other.getOidcEnabled());
      }
      if (other.getApiKeyEnabled() != false) {
        setApiKeyEnabled(other.getApiKeyEnabled());
      }
      if (other.getAdminJustificationRequired() != false) {
        setAdminJustificationRequired(other.getAdminJustificationRequired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              oidcEnabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              apiKeyEnabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              adminJustificationRequired_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean oidcEnabled_ ;
    /**
     * <code>bool oidc_enabled = 1;</code>
     * @return The oidcEnabled.
     */
    @java.lang.Override
    public boolean getOidcEnabled() {
      return oidcEnabled_;
    }
    /**
     * <code>bool oidc_enabled = 1;</code>
     * @param value The oidcEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setOidcEnabled(boolean value) {

      oidcEnabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool oidc_enabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOidcEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      oidcEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean apiKeyEnabled_ ;
    /**
     * <code>bool api_key_enabled = 2;</code>
     * @return The apiKeyEnabled.
     */
    @java.lang.Override
    public boolean getApiKeyEnabled() {
      return apiKeyEnabled_;
    }
    /**
     * <code>bool api_key_enabled = 2;</code>
     * @param value The apiKeyEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setApiKeyEnabled(boolean value) {

      apiKeyEnabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool api_key_enabled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearApiKeyEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      apiKeyEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean adminJustificationRequired_ ;
    /**
     * <code>bool admin_justification_required = 3;</code>
     * @return The adminJustificationRequired.
     */
    @java.lang.Override
    public boolean getAdminJustificationRequired() {
      return adminJustificationRequired_;
    }
    /**
     * <code>bool admin_justification_required = 3;</code>
     * @param value The adminJustificationRequired to set.
     * @return This builder for chaining.
     */
    public Builder setAdminJustificationRequired(boolean value) {

      adminJustificationRequired_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool admin_justification_required = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdminJustificationRequired() {
      bitField0_ = (bitField0_ & ~0x00000004);
      adminJustificationRequired_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.CapabilitiesAuth)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.CapabilitiesAuth)
  private static final io.github.chirino.memory.grpc.v1.CapabilitiesAuth DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.CapabilitiesAuth();
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesAuth getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CapabilitiesAuth>
      PARSER = new com.google.protobuf.AbstractParser<CapabilitiesAuth>() {
    @java.lang.Override
    public CapabilitiesAuth parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CapabilitiesAuth> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CapabilitiesAuth> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.CapabilitiesAuth getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

