// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * Protobuf type {@code memory.v1.CapabilitiesFeatures}
 */
public final class CapabilitiesFeatures extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:memory.v1.CapabilitiesFeatures)
    CapabilitiesFeaturesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CapabilitiesFeatures.newBuilder() to construct.
  private CapabilitiesFeatures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CapabilitiesFeatures() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CapabilitiesFeatures();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesFeatures_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesFeatures_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.class, io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.Builder.class);
  }

  public static final int OUTBOX_ENABLED_FIELD_NUMBER = 1;
  private boolean outboxEnabled_ = false;
  /**
   * <code>bool outbox_enabled = 1;</code>
   * @return The outboxEnabled.
   */
  @java.lang.Override
  public boolean getOutboxEnabled() {
    return outboxEnabled_;
  }

  public static final int SEMANTIC_SEARCH_ENABLED_FIELD_NUMBER = 2;
  private boolean semanticSearchEnabled_ = false;
  /**
   * <code>bool semantic_search_enabled = 2;</code>
   * @return The semanticSearchEnabled.
   */
  @java.lang.Override
  public boolean getSemanticSearchEnabled() {
    return semanticSearchEnabled_;
  }

  public static final int FULLTEXT_SEARCH_ENABLED_FIELD_NUMBER = 3;
  private boolean fulltextSearchEnabled_ = false;
  /**
   * <code>bool fulltext_search_enabled = 3;</code>
   * @return The fulltextSearchEnabled.
   */
  @java.lang.Override
  public boolean getFulltextSearchEnabled() {
    return fulltextSearchEnabled_;
  }

  public static final int CORS_ENABLED_FIELD_NUMBER = 4;
  private boolean corsEnabled_ = false;
  /**
   * <code>bool cors_enabled = 4;</code>
   * @return The corsEnabled.
   */
  @java.lang.Override
  public boolean getCorsEnabled() {
    return corsEnabled_;
  }

  public static final int MANAGEMENT_LISTENER_ENABLED_FIELD_NUMBER = 5;
  private boolean managementListenerEnabled_ = false;
  /**
   * <code>bool management_listener_enabled = 5;</code>
   * @return The managementListenerEnabled.
   */
  @java.lang.Override
  public boolean getManagementListenerEnabled() {
    return managementListenerEnabled_;
  }

  public static final int PRIVATE_SOURCE_URLS_ENABLED_FIELD_NUMBER = 6;
  private boolean privateSourceUrlsEnabled_ = false;
  /**
   * <code>bool private_source_urls_enabled = 6;</code>
   * @return The privateSourceUrlsEnabled.
   */
  @java.lang.Override
  public boolean getPrivateSourceUrlsEnabled() {
    return privateSourceUrlsEnabled_;
  }

  public static final int S3_DIRECT_DOWNLOAD_ENABLED_FIELD_NUMBER = 7;
  private boolean s3DirectDownloadEnabled_ = false;
  /**
   * <code>bool s3_direct_download_enabled = 7;</code>
   * @return The s3DirectDownloadEnabled.
   */
  @java.lang.Override
  public boolean getS3DirectDownloadEnabled() {
    return s3DirectDownloadEnabled_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (outboxEnabled_ != false) {
      output.writeBool(1, outboxEnabled_);
    }
    if (semanticSearchEnabled_ != false) {
      output.writeBool(2, semanticSearchEnabled_);
    }
    if (fulltextSearchEnabled_ != false) {
      output.writeBool(3, fulltextSearchEnabled_);
    }
    if (corsEnabled_ != false) {
      output.writeBool(4, corsEnabled_);
    }
    if (managementListenerEnabled_ != false) {
      output.writeBool(5, managementListenerEnabled_);
    }
    if (privateSourceUrlsEnabled_ != false) {
      output.writeBool(6, privateSourceUrlsEnabled_);
    }
    if (s3DirectDownloadEnabled_ != false) {
      output.writeBool(7, s3DirectDownloadEnabled_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (outboxEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, outboxEnabled_);
    }
    if (semanticSearchEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, semanticSearchEnabled_);
    }
    if (fulltextSearchEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, fulltextSearchEnabled_);
    }
    if (corsEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, corsEnabled_);
    }
    if (managementListenerEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, managementListenerEnabled_);
    }
    if (privateSourceUrlsEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, privateSourceUrlsEnabled_);
    }
    if (s3DirectDownloadEnabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, s3DirectDownloadEnabled_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.chirino.memory.grpc.v1.CapabilitiesFeatures)) {
      return super.equals(obj);
    }
    io.github.chirino.memory.grpc.v1.CapabilitiesFeatures other = (io.github.chirino.memory.grpc.v1.CapabilitiesFeatures) obj;

    if (getOutboxEnabled()
        != other.getOutboxEnabled()) return false;
    if (getSemanticSearchEnabled()
        != other.getSemanticSearchEnabled()) return false;
    if (getFulltextSearchEnabled()
        != other.getFulltextSearchEnabled()) return false;
    if (getCorsEnabled()
        != other.getCorsEnabled()) return false;
    if (getManagementListenerEnabled()
        != other.getManagementListenerEnabled()) return false;
    if (getPrivateSourceUrlsEnabled()
        != other.getPrivateSourceUrlsEnabled()) return false;
    if (getS3DirectDownloadEnabled()
        != other.getS3DirectDownloadEnabled()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + OUTBOX_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOutboxEnabled());
    hash = (37 * hash) + SEMANTIC_SEARCH_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSemanticSearchEnabled());
    hash = (37 * hash) + FULLTEXT_SEARCH_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFulltextSearchEnabled());
    hash = (37 * hash) + CORS_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCorsEnabled());
    hash = (37 * hash) + MANAGEMENT_LISTENER_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getManagementListenerEnabled());
    hash = (37 * hash) + PRIVATE_SOURCE_URLS_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPrivateSourceUrlsEnabled());
    hash = (37 * hash) + S3_DIRECT_DOWNLOAD_ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getS3DirectDownloadEnabled());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.chirino.memory.grpc.v1.CapabilitiesFeatures prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code memory.v1.CapabilitiesFeatures}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:memory.v1.CapabilitiesFeatures)
      io.github.chirino.memory.grpc.v1.CapabilitiesFeaturesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesFeatures_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesFeatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.class, io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.Builder.class);
    }

    // Construct using io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      outboxEnabled_ = false;
      semanticSearchEnabled_ = false;
      fulltextSearchEnabled_ = false;
      corsEnabled_ = false;
      managementListenerEnabled_ = false;
      privateSourceUrlsEnabled_ = false;
      s3DirectDownloadEnabled_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.chirino.memory.grpc.v1.MemoryService.internal_static_memory_v1_CapabilitiesFeatures_descriptor;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesFeatures getDefaultInstanceForType() {
      return io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesFeatures build() {
      io.github.chirino.memory.grpc.v1.CapabilitiesFeatures result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.chirino.memory.grpc.v1.CapabilitiesFeatures buildPartial() {
      io.github.chirino.memory.grpc.v1.CapabilitiesFeatures result = new io.github.chirino.memory.grpc.v1.CapabilitiesFeatures(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.github.chirino.memory.grpc.v1.CapabilitiesFeatures result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.outboxEnabled_ = outboxEnabled_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.semanticSearchEnabled_ = semanticSearchEnabled_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.fulltextSearchEnabled_ = fulltextSearchEnabled_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.corsEnabled_ = corsEnabled_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.managementListenerEnabled_ = managementListenerEnabled_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.privateSourceUrlsEnabled_ = privateSourceUrlsEnabled_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.s3DirectDownloadEnabled_ = s3DirectDownloadEnabled_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.chirino.memory.grpc.v1.CapabilitiesFeatures) {
        return mergeFrom((io.github.chirino.memory.grpc.v1.CapabilitiesFeatures)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.chirino.memory.grpc.v1.CapabilitiesFeatures other) {
      if (other == io.github.chirino.memory.grpc.v1.CapabilitiesFeatures.getDefaultInstance()) return this;
      if (other.getOutboxEnabled() != false) {
        setOutboxEnabled(other.getOutboxEnabled());
      }
      if (other.getSemanticSearchEnabled() != false) {
        setSemanticSearchEnabled(other.getSemanticSearchEnabled());
      }
      if (other.getFulltextSearchEnabled() != false) {
        setFulltextSearchEnabled(other.getFulltextSearchEnabled());
      }
      if (other.getCorsEnabled() != false) {
        setCorsEnabled(other.getCorsEnabled());
      }
      if (other.getManagementListenerEnabled() != false) {
        setManagementListenerEnabled(other.getManagementListenerEnabled());
      }
      if (other.getPrivateSourceUrlsEnabled() != false) {
        setPrivateSourceUrlsEnabled(other.getPrivateSourceUrlsEnabled());
      }
      if (other.getS3DirectDownloadEnabled() != false) {
        setS3DirectDownloadEnabled(other.getS3DirectDownloadEnabled());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              outboxEnabled_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              semanticSearchEnabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              fulltextSearchEnabled_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              corsEnabled_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              managementListenerEnabled_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              privateSourceUrlsEnabled_ = input.readBool();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              s3DirectDownloadEnabled_ = input.readBool();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean outboxEnabled_ ;
    /**
     * <code>bool outbox_enabled = 1;</code>
     * @return The outboxEnabled.
     */
    @java.lang.Override
    public boolean getOutboxEnabled() {
      return outboxEnabled_;
    }
    /**
     * <code>bool outbox_enabled = 1;</code>
     * @param value The outboxEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setOutboxEnabled(boolean value) {

      outboxEnabled_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool outbox_enabled = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearOutboxEnabled() {
      bitField0_ = (bitField0_ & ~0x00000001);
      outboxEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean semanticSearchEnabled_ ;
    /**
     * <code>bool semantic_search_enabled = 2;</code>
     * @return The semanticSearchEnabled.
     */
    @java.lang.Override
    public boolean getSemanticSearchEnabled() {
      return semanticSearchEnabled_;
    }
    /**
     * <code>bool semantic_search_enabled = 2;</code>
     * @param value The semanticSearchEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setSemanticSearchEnabled(boolean value) {

      semanticSearchEnabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool semantic_search_enabled = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSemanticSearchEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      semanticSearchEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean fulltextSearchEnabled_ ;
    /**
     * <code>bool fulltext_search_enabled = 3;</code>
     * @return The fulltextSearchEnabled.
     */
    @java.lang.Override
    public boolean getFulltextSearchEnabled() {
      return fulltextSearchEnabled_;
    }
    /**
     * <code>bool fulltext_search_enabled = 3;</code>
     * @param value The fulltextSearchEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setFulltextSearchEnabled(boolean value) {

      fulltextSearchEnabled_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool fulltext_search_enabled = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearFulltextSearchEnabled() {
      bitField0_ = (bitField0_ & ~0x00000004);
      fulltextSearchEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean corsEnabled_ ;
    /**
     * <code>bool cors_enabled = 4;</code>
     * @return The corsEnabled.
     */
    @java.lang.Override
    public boolean getCorsEnabled() {
      return corsEnabled_;
    }
    /**
     * <code>bool cors_enabled = 4;</code>
     * @param value The corsEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setCorsEnabled(boolean value) {

      corsEnabled_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>bool cors_enabled = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCorsEnabled() {
      bitField0_ = (bitField0_ & ~0x00000008);
      corsEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean managementListenerEnabled_ ;
    /**
     * <code>bool management_listener_enabled = 5;</code>
     * @return The managementListenerEnabled.
     */
    @java.lang.Override
    public boolean getManagementListenerEnabled() {
      return managementListenerEnabled_;
    }
    /**
     * <code>bool management_listener_enabled = 5;</code>
     * @param value The managementListenerEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setManagementListenerEnabled(boolean value) {

      managementListenerEnabled_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool management_listener_enabled = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearManagementListenerEnabled() {
      bitField0_ = (bitField0_ & ~0x00000010);
      managementListenerEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean privateSourceUrlsEnabled_ ;
    /**
     * <code>bool private_source_urls_enabled = 6;</code>
     * @return The privateSourceUrlsEnabled.
     */
    @java.lang.Override
    public boolean getPrivateSourceUrlsEnabled() {
      return privateSourceUrlsEnabled_;
    }
    /**
     * <code>bool private_source_urls_enabled = 6;</code>
     * @param value The privateSourceUrlsEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setPrivateSourceUrlsEnabled(boolean value) {

      privateSourceUrlsEnabled_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>bool private_source_urls_enabled = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrivateSourceUrlsEnabled() {
      bitField0_ = (bitField0_ & ~0x00000020);
      privateSourceUrlsEnabled_ = false;
      onChanged();
      return this;
    }

    private boolean s3DirectDownloadEnabled_ ;
    /**
     * <code>bool s3_direct_download_enabled = 7;</code>
     * @return The s3DirectDownloadEnabled.
     */
    @java.lang.Override
    public boolean getS3DirectDownloadEnabled() {
      return s3DirectDownloadEnabled_;
    }
    /**
     * <code>bool s3_direct_download_enabled = 7;</code>
     * @param value The s3DirectDownloadEnabled to set.
     * @return This builder for chaining.
     */
    public Builder setS3DirectDownloadEnabled(boolean value) {

      s3DirectDownloadEnabled_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>bool s3_direct_download_enabled = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearS3DirectDownloadEnabled() {
      bitField0_ = (bitField0_ & ~0x00000040);
      s3DirectDownloadEnabled_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:memory.v1.CapabilitiesFeatures)
  }

  // @@protoc_insertion_point(class_scope:memory.v1.CapabilitiesFeatures)
  private static final io.github.chirino.memory.grpc.v1.CapabilitiesFeatures DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.chirino.memory.grpc.v1.CapabilitiesFeatures();
  }

  public static io.github.chirino.memory.grpc.v1.CapabilitiesFeatures getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CapabilitiesFeatures>
      PARSER = new com.google.protobuf.AbstractParser<CapabilitiesFeatures>() {
    @java.lang.Override
    public CapabilitiesFeatures parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CapabilitiesFeatures> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CapabilitiesFeatures> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.chirino.memory.grpc.v1.CapabilitiesFeatures getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

