// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

/**
 * <pre>
 * ConversationListMode controls which conversations are returned from each fork tree.
 * Conversations can be forked to create branches. All forks share the same
 * "conversation group" (fork tree). This mode determines which conversations
 * from each fork tree are included in list results.
 * </pre>
 *
 * Protobuf enum {@code memory.v1.ConversationListMode}
 */
public enum ConversationListMode
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Unspecified defaults to LATEST_FORK.
   * </pre>
   *
   * <code>CONVERSATION_LIST_MODE_UNSPECIFIED = 0;</code>
   */
  CONVERSATION_LIST_MODE_UNSPECIFIED(0),
  /**
   * <pre>
   * Include all conversations the user can access (roots and forks).
   * </pre>
   *
   * <code>ALL = 1;</code>
   */
  ALL(1),
  /**
   * <pre>
   * Only include root conversations (conversations that are not forks).
   * </pre>
   *
   * <code>ROOTS = 2;</code>
   */
  ROOTS(2),
  /**
   * <pre>
   * Include only the most recently updated conversation per fork tree (default).
   * This is useful for showing a single representative conversation from each tree.
   * </pre>
   *
   * <code>LATEST_FORK = 3;</code>
   */
  LATEST_FORK(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Unspecified defaults to LATEST_FORK.
   * </pre>
   *
   * <code>CONVERSATION_LIST_MODE_UNSPECIFIED = 0;</code>
   */
  public static final int CONVERSATION_LIST_MODE_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Include all conversations the user can access (roots and forks).
   * </pre>
   *
   * <code>ALL = 1;</code>
   */
  public static final int ALL_VALUE = 1;
  /**
   * <pre>
   * Only include root conversations (conversations that are not forks).
   * </pre>
   *
   * <code>ROOTS = 2;</code>
   */
  public static final int ROOTS_VALUE = 2;
  /**
   * <pre>
   * Include only the most recently updated conversation per fork tree (default).
   * This is useful for showing a single representative conversation from each tree.
   * </pre>
   *
   * <code>LATEST_FORK = 3;</code>
   */
  public static final int LATEST_FORK_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ConversationListMode valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ConversationListMode forNumber(int value) {
    switch (value) {
      case 0: return CONVERSATION_LIST_MODE_UNSPECIFIED;
      case 1: return ALL;
      case 2: return ROOTS;
      case 3: return LATEST_FORK;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ConversationListMode>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ConversationListMode> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ConversationListMode>() {
          public ConversationListMode findValueByNumber(int number) {
            return ConversationListMode.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return io.github.chirino.memory.grpc.v1.MemoryService.getDescriptor().getEnumTypes().get(0);
  }

  private static final ConversationListMode[] VALUES = values();

  public static ConversationListMode valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ConversationListMode(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:memory.v1.ConversationListMode)
}

