// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface EntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.Entry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Unique identifier (UUID as 16-byte big-endian binary)
   * </pre>
   *
   * <code>bytes id = 1;</code>
   * @return The id.
   */
  com.google.protobuf.ByteString getId();

  /**
   * <pre>
   * Conversation identifier
   * </pre>
   *
   * <code>string conversation_id = 2;</code>
   * @return The conversationId.
   */
  java.lang.String getConversationId();
  /**
   * <pre>
   * Conversation identifier
   * </pre>
   *
   * <code>string conversation_id = 2;</code>
   * @return The bytes for conversationId.
   */
  com.google.protobuf.ByteString
      getConversationIdBytes();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>.memory.v1.Channel channel = 4;</code>
   * @return The enum numeric value on the wire for channel.
   */
  int getChannelValue();
  /**
   * <code>.memory.v1.Channel channel = 4;</code>
   * @return The channel.
   */
  io.github.chirino.memory.grpc.v1.Channel getChannel();

  /**
   * <code>int64 epoch = 5;</code>
   * @return The epoch.
   */
  long getEpoch();

  /**
   * <pre>
   * Describes the schema/format of the content array.
   * History channel entries must use "history" as the content_type.
   * The content array for history entries contains objects with:
   *   - text (string): The message text.
   *   - role (string): Either "USER" or "AI".
   * Other content_types (e.g., "LC4J", "SpringAI") may be used for
   * agent context entries.
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   * Describes the schema/format of the content array.
   * History channel entries must use "history" as the content_type.
   * The content array for history entries contains objects with:
   *   - text (string): The message text.
   *   - role (string): Either "USER" or "AI".
   * Other content_types (e.g., "LC4J", "SpringAI") may be used for
   * agent context entries.
   * </pre>
   *
   * <code>string content_type = 6;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   * For history channel entries (content_type: "history"), each block
   * contains text and role fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Value content = 7;</code>
   */
  java.util.List<com.google.protobuf.Value> 
      getContentList();
  /**
   * <pre>
   * For history channel entries (content_type: "history"), each block
   * contains text and role fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Value content = 7;</code>
   */
  com.google.protobuf.Value getContent(int index);
  /**
   * <pre>
   * For history channel entries (content_type: "history"), each block
   * contains text and role fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Value content = 7;</code>
   */
  int getContentCount();
  /**
   * <pre>
   * For history channel entries (content_type: "history"), each block
   * contains text and role fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Value content = 7;</code>
   */
  java.util.List<? extends com.google.protobuf.ValueOrBuilder> 
      getContentOrBuilderList();
  /**
   * <pre>
   * For history channel entries (content_type: "history"), each block
   * contains text and role fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Value content = 7;</code>
   */
  com.google.protobuf.ValueOrBuilder getContentOrBuilder(
      int index);

  /**
   * <code>string created_at = 8;</code>
   * @return The createdAt.
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string created_at = 8;</code>
   * @return The bytes for createdAt.
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();
}
