// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface MemoryNamespaceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.MemoryNamespace)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string segments = 1;</code>
   * @return A list containing the segments.
   */
  java.util.List<java.lang.String>
      getSegmentsList();
  /**
   * <code>repeated string segments = 1;</code>
   * @return The count of segments.
   */
  int getSegmentsCount();
  /**
   * <code>repeated string segments = 1;</code>
   * @param index The index of the element to return.
   * @return The segments at the given index.
   */
  java.lang.String getSegments(int index);
  /**
   * <code>repeated string segments = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the segments at the given index.
   */
  com.google.protobuf.ByteString
      getSegmentsBytes(int index);
}
