// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface MemoryUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.MemoryUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 fetch_count = 1;</code>
   * @return The fetchCount.
   */
  long getFetchCount();

  /**
   * <code>.google.protobuf.Timestamp last_fetched_at = 2;</code>
   * @return Whether the lastFetchedAt field is set.
   */
  boolean hasLastFetchedAt();
  /**
   * <code>.google.protobuf.Timestamp last_fetched_at = 2;</code>
   * @return The lastFetchedAt.
   */
  com.google.protobuf.Timestamp getLastFetchedAt();
  /**
   * <code>.google.protobuf.Timestamp last_fetched_at = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastFetchedAtOrBuilder();
}
