// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface PageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.PageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string page_token = 1;</code>
   * @return The pageToken.
   */
  java.lang.String getPageToken();
  /**
   * <code>string page_token = 1;</code>
   * @return The bytes for pageToken.
   */
  com.google.protobuf.ByteString
      getPageTokenBytes();

  /**
   * <code>int32 page_size = 2;</code>
   * @return The pageSize.
   */
  int getPageSize();
}
