// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface ReplayResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.ReplayResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Content chunk
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <pre>
   * Content chunk
   * </pre>
   *
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <pre>
   * Set when redirect is needed (format: "host:port")
   * </pre>
   *
   * <code>string redirect_address = 2;</code>
   * @return The redirectAddress.
   */
  java.lang.String getRedirectAddress();
  /**
   * <pre>
   * Set when redirect is needed (format: "host:port")
   * </pre>
   *
   * <code>string redirect_address = 2;</code>
   * @return The bytes for redirectAddress.
   */
  com.google.protobuf.ByteString
      getRedirectAddressBytes();
}
