// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface RequestActorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.RequestActor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string on_behalf_of_user_id = 1;</code>
   * @return Whether the onBehalfOfUserId field is set.
   */
  boolean hasOnBehalfOfUserId();
  /**
   * <code>optional string on_behalf_of_user_id = 1;</code>
   * @return The onBehalfOfUserId.
   */
  java.lang.String getOnBehalfOfUserId();
  /**
   * <code>optional string on_behalf_of_user_id = 1;</code>
   * @return The bytes for onBehalfOfUserId.
   */
  com.google.protobuf.ByteString
      getOnBehalfOfUserIdBytes();
}
