// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface SearchEntriesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.SearchEntriesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string query = 1;</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1;</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();

  /**
   * <pre>
   * Cursor for pagination; returns items after this result
   * </pre>
   *
   * <code>string after = 2;</code>
   * @return The after.
   */
  java.lang.String getAfter();
  /**
   * <pre>
   * Cursor for pagination; returns items after this result
   * </pre>
   *
   * <code>string after = 2;</code>
   * @return The bytes for after.
   */
  com.google.protobuf.ByteString
      getAfterBytes();

  /**
   * <pre>
   * Maximum number of results to return (default 20)
   * </pre>
   *
   * <code>int32 limit = 3;</code>
   * @return The limit.
   */
  int getLimit();

  /**
   * <pre>
   * Whether to include the full entry in results. Defaults to true.
   * </pre>
   *
   * <code>optional bool include_entry = 4;</code>
   * @return Whether the includeEntry field is set.
   */
  boolean hasIncludeEntry();
  /**
   * <pre>
   * Whether to include the full entry in results. Defaults to true.
   * </pre>
   *
   * <code>optional bool include_entry = 4;</code>
   * @return The includeEntry.
   */
  boolean getIncludeEntry();
}
