// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: memory/v1/memory_service.proto

// Protobuf Java Version: 3.25.5
package io.github.chirino.memory.grpc.v1;

public interface TopMemoryUsageItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:memory.v1.TopMemoryUsageItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string namespace = 1;</code>
   * @return A list containing the namespace.
   */
  java.util.List<java.lang.String>
      getNamespaceList();
  /**
   * <code>repeated string namespace = 1;</code>
   * @return The count of namespace.
   */
  int getNamespaceCount();
  /**
   * <code>repeated string namespace = 1;</code>
   * @param index The index of the element to return.
   * @return The namespace at the given index.
   */
  java.lang.String getNamespace(int index);
  /**
   * <code>repeated string namespace = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the namespace at the given index.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes(int index);

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.memory.v1.MemoryUsage usage = 3;</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <code>.memory.v1.MemoryUsage usage = 3;</code>
   * @return The usage.
   */
  io.github.chirino.memory.grpc.v1.MemoryUsage getUsage();
  /**
   * <code>.memory.v1.MemoryUsage usage = 3;</code>
   */
  io.github.chirino.memory.grpc.v1.MemoryUsageOrBuilder getUsageOrBuilder();
}
